.gitignore
README.md
service/src/intTest/resources/application.yml

* Enhanced documentation about how to run integration tests with external services in-the-loop
* Added a default mongo URI for intTest

NIAD-759 Documentation to support testing of object store

---

service/src/main/resources/templates/ehr_medication_statement_authorise_template.mustache
service/src/main/resources/templates/ehr_medication_statement_prescribe_template.mustache
service/src/test/resources/ehr/mapper/encountercomponents/expected-components-1.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-active-status.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-acute-prescription.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-default-status-reason-code.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-no-optional-fields.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-optional-fields.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-repeat-prescription-no-value.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-repeat-prescription.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-start-period-only.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-complete-status.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-dispense-quantity-text.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-no-dispense-quantity-text.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-no-dispense-quantity-value.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-prescribe-based-on.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-prescribe-no-optional-fields.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-prescribe-optional-fields.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-prescribe-prior-prescription.xml
service/src/test/resources/ehr/request/fhir/output/expected-ehr-extract-response-from-json.xml
service/src/test/resources/uat/output/TC4-9465698490_Daniels_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465698679_Gainsford_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465699918_Magre_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465699926_Sajal_full_20210122.xml
service/src/test/resources/uat/output/TC4-9465700339_Yamura_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465701262_Meyers_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465701297_Livermore_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465701459_Nel_full_20210119.xml

https://gpitbjss.atlassian.net/browse/NIAD-1427
Solved with a regex search and replace across the codebase:
Search
`<component typeCode="COMP" contextConductionInd="true">(\s*)<MedicationStatement `
Replace
`<component typeCode="COMP">$1<MedicationStatement `
The capture group and `$1` reference ensure the whitespace between tags is retained.

NIAD-1427: Remove @contextConductionInd from MedicationStatement components

---

service/src/main/resources/templates/ehr_encounter_to_ehr_composition_template.mustache
service/src/test/resources/ehr/request/fhir/output/ExpectedResponseFrom1ConsultationResponse.xml
service/src/test/resources/ehr/request/fhir/output/expected-ehr-extract-response-from-json.xml
service/src/test/resources/ehr/request/fhir/output/expected-xml-without-effective-time.xml
service/src/test/resources/uat/output/TC4-9465698490_Daniels_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465698679_Gainsford_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465699918_Magre_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465699926_Sajal_full_20210122.xml
service/src/test/resources/uat/output/TC4-9465700193_Birdi_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465700339_Yamura_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465701262_Meyers_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465701297_Livermore_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465701459_Nel_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465701483_Dougill_full_20210119.xml
service/src/test/resources/uat/output/TC4-9465701483_Nel_full_20210119.xml

JIRA: https://gpitbjss.atlassian.net/browse/NIAD-1398
- Update `ehr_encounter_to_ehr_composition_template.mustache` used by EncounterMapper and NonConsultationResourceMapper, to replace Participant2 and author agent id mapping with `<id nullFlavor="UNK"/>` when id is null
- Update unit tests xml output

NIAD-1398: handle missing agents on ehrComposition

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DiaryPlanStatementMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/NonConsultationResourceMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DiaryPlanStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/NonConsultationResourceMapperTest.java

The workaround was deemed the appropriate way to handle the situation of a
mapper returning empty/blank values. However, empty `Optional`s were taken
as an improvement over possibly-blank strings.

NIAD-1410: Optionalise mappings

---

service/src/test/java/uk/nhs/adaptors/gp2gp/common/task/TaskHandlerTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/mhs/InboundMessageHandlerTest.java

Extend unit tests to verify that message processing is aborted when message can't be read.

NIAD-1166 Verify that message processing is aborted when message can't be read

---

service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/TaskHandlingTest.java

These tests are focused on handling task messages and their purpose is to verify such things as acknowledging queue message, (the fact of) executing a task and failing the process/conversation.

NIAD-1166: create integration tests for the handling of task messages

---

service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/InboundMessageHandlingTest.java

These tests are focused on handling inbound messages and their purpose is to verify such things as acknowledging queue message, (the fact of) processing the message and failing the process/conversation.

NIAD-1166: create integration tests for the handling of inbound messages

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterMapper.java
service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-10.xml
service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-8.xml

- In the case of unrecognised encounter code, the original text should first be provided by the .text value (If it is present) otherwise the .display value should be used (always present.)

NIAD-1583: Unrecognised encounter codes should display the original term text

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/BloodPressureMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationStatementMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/StatementTimeMappingUtils.java
service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-with-data.xml
service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-with-diastolic-data-only.xml
service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-with-period-date.xml
service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-with-systolic-data-only.xml
service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-without-data.xml
service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-without-effective-date.xml
service/src/test/resources/ehr/mapper/blood_pressure/blood-pressure-with-codeable-concepts.xml
service/src/test/resources/ehr/request/fhir/output/expected-ehr-extract-response-from-json.xml
service/src/test/resources/uat/output/TC4/9465699926_Sajal_full_20210122.xml
service/src/test/resources/uat/output/TC4/9465700339_Yamura_full_20210119.xml
service/src/test/resources/uat/output/TC4/9465701297_Livermore_full_20210119.xml
service/src/test/resources/uat/output/TC4/9465701483_Dougill_full_20210119.xml
service/src/test/resources/uat/output/TC4/9465701483_Nel_full_20210119.xml
service/src/test/resources/uat/output/TC7/9465700339_Yamura_full_20210602.xml
service/src/test/resources/uat/output/TC7/9465701297_Livermore_full_20210602.xml
service/src/test/resources/uat/output/TC7/9465701459_Nel_full_20210602.xml
service/src/test/resources/uat/output/TC7/9465701483_Dougill_full_20210602.xml

- Bug [NIAD-1719](https://gpitbjss.atlassian.net/browse/NIAD-1719)
- The ticket describes an issue around effectiveTime for BloodPressure based Observations. However this functionality was already fixed, and this PR is more focused on the availabilityTime of the BloodPressure observation. Aligning them with that of normal Observations that was brought in in [NIAD-1559](https://github.com/nhsconnect/integration-adaptor-gp2gp/pull/324)

NIAD-1719: BloodPressure: Exception when no effectivePeriod.start

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapperTest.java
service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_1.xml
service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_2.xml
service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_3.xml
service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_with_data_absent_reason_and_interpretation_and_body_site_and_method.xml
service/src/test/resources/ehr/mapper/encountercomponents/expected-components-1.xml
service/src/test/resources/ehr/request/fhir/output/expected-xml-with-observations-inside-report.xml
service/src/test/resources/uat/output/TC4/9465700088_Mold_full_20210119.xml
service/src/test/resources/uat/output/TC4/9465701718_Guerra_full_20210119.xml
service/src/test/resources/uat/output/TC7/9465700088_Mold_full_20210602.xml
service/src/test/resources/uat/output/TC7/9465701718_Guerra_full_20210602.xml

[NIAD-1759](https://gpitbjss.atlassian.net/browse/NIAD-1759) fix
- Comments in Observations that contain USER_COMMENT_CODE are treated as USER_COMMENT CommentType

NIAD-1759: DiagnosticReport: User comments handling in narrative statement

---

smoke-tests/src/test/java/util/EnvVarsUtil.java

Fix bug where gpc smoke test will not extract host from url if the host is not a docker container.

NIAD-2188 smoke test - string replacement bug

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AgentPersonMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/PractitionerAgentPersonMapperParameters.java
service/src/main/resources/templates/ehr_agent_person_template.mustache
service/src/test/resources/ehr/mapper/practitioner/practitioner-only/practitioner-full-name-and-unstructured.json
service/src/test/resources/ehr/mapper/practitioner/practitioner-only/practitioner-full-name-and-unstructured.xml
service/src/test/resources/ehr/mapper/practitioner/practitioner-only/practitioner-unstructured-only.json
service/src/test/resources/ehr/mapper/practitioner/practitioner-only/practitioner-unstructured-only.xml

During the investigation for this ticket, it was found practitioners with an unstructured name, as below;
```
"name": [
{
"use": "official",
"text": "Nick Matthews"
}
]
```
were mapped to the EHR agent element with an unknown name:
```
<name>
<family>Unknown</family>
</name>
```
The mapping has been altered, so that if the `family` and `given` name elements are not present, the `text` element will be used. Therefore, the example above will be mapped to an unstructured name element, as follows:
```
<name>Nick Matthews</name>
```

NIAD-2398 Mapping bug: practitioner missing

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementExtractor.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/MedicationStatementTemplateParameters.java
service/src/main/resources/templates/ehr_medication_statement_authorise_template.mustache
service/src/main/resources/templates/ehr_medication_statement_prescribe_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapperTest.java
service/src/test/resources/ehr/mapper/medication_request/fhir-bundle-with-medication-statements.json
service/src/test/resources/ehr/mapper/medication_request/medication-request-empty-prescribing-agency-coding-array.json
service/src/test/resources/ehr/mapper/medication_request/medication-request-missing-prescribing-agency-codeable-concept.json
service/src/test/resources/ehr/mapper/medication_request/medication-request-prescribed-by-another-organisation.json
service/src/test/resources/ehr/mapper/medication_request/medication-request-prescribed-by-gp-practice.json
service/src/test/resources/ehr/mapper/medication_request/medication-request-prescribed-by-previous-practice.json
service/src/test/resources/ehr/mapper/medication_request/medication-statement-nhs-prescription.xml
service/src/test/resources/ehr/mapper/medication_request/medication-statement-prescribed-by-another-organisation.xml

*Description*
Within the GP2GP message created from the Medicus E2E test, Peter Salisbury has identified that the SNOMED code used in <ehrSupplyAuthorise> for the “Prescribed  elsewhere” medication is incorrect. 
This line 537…
```
<code code="394823007" displayName="NHS Prescription" codeSystem="2.16.840.1.113883.2.1.3.2.4.15"/>
```                                               
should be…
```
<code code="394828003" displayName="Prescription by another organisation" codeSystem="2.16.840.1.113883.2.1.3.2.4.15"/> 
```

NIAD-2421 Prescribed Elsewhere has the wrong SNOMED code.

---

e2e-tests/src/test/java/uk/nhs/adaptors/gp2gp/e2e/model/EhrStatus.java
service/src/intTest/java/uk/nhs/adaptors/gp2gp/common/amqp/AmqpServiceFailureTest.java
service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/status/EhrStatusEndpointTest.java
service/src/intTest/java/uk/nhs/adaptors/gp2gp/util/ProcessDetectionService.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/status/model/EhrStatus.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/status/service/EhrStatusService.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/status/service/EhrStatusServiceTest.java

Since the introduction on the ASID override variables in the GP2GP adaptor, it is possible to lose the original ASID provided by the given EHR message.
Scenerio 1
GIVEN an EHR request is received
THEN the toASID and fromASID fields should be recorded against the EHR in the Database. 
Scenerio 2
Given a request is made to the status endpoint for a given Conversation ID
THEN the toAsid and fromAsid fields original given for the EHR request should be returned in the json e.g.
{
fromASID: “…“,
toASID: “….“
….
}

NIAD-2402: Add fromAsid and toAsid to EHR status endpoint.

---

docker/wiremock/stubs/__files/correctPatientStructuredRecordResponseBodySite.json
docker/wiremock/stubs/mappings/retrievePatientStructuredRecordBodySite.json
e2e-tests/src/test/java/uk/nhs/adaptors/gp2gp/e2e/EhrExtractTest.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationStatementMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationStatementMapperTest.java
service/src/test/resources/ehr/mapper/observation/example-observation-with-body-site.json
service/src/test/resources/ehr/mapper/observation/expected-output-observation-with-body-site.xml

Development Task: When we receive an entry with a Bodysite parameter, we should map the display text of the bodysite to the text/comment section of the parent entry prefixed with “BodySite:”, translating this across into the HL7 format. 
Update Observation statement mapper to map body site correctly 
Add example json to WireMock
Add example test files for parameterised test
Add E2E test for Body Site Mapping

NIAD-2580 - Run1 Cycle1 - Body Site value under Procedure is not displayed 

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/NonConsultationResourceMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/NonConsultationResourceMapperTest.java
service/src/test/resources/ehr/mapper/encountercomponents/contained-resources/input-not-referenced.json
service/src/test/resources/ehr/mapper/encountercomponents/contained-resources/input-referenced-in-category.json
service/src/test/resources/ehr/mapper/encountercomponents/contained-resources/input-referenced-in-topic.json
service/src/test/resources/ehr/mapper/encountercomponents/contained-resources/input-referenced-observation.json
service/src/test/resources/ehr/mapper/encountercomponents/contained-resources/input-topic-and-category.json
service/src/test/resources/ehr/mapper/encountercomponents/contained-resources/input-two-resources-category.json
service/src/test/resources/ehr/mapper/encountercomponents/contained-resources/output-referenced-in-category.xml
service/src/test/resources/ehr/mapper/encountercomponents/contained-resources/output-referenced-in-topic.xml
service/src/test/resources/ehr/mapper/encountercomponents/contained-resources/output-referenced-observation.xml
service/src/test/resources/ehr/mapper/encountercomponents/contained-resources/output-topic-and-category.xml
service/src/test/resources/ehr/mapper/encountercomponents/contained-resources/output-two-resources-category.xml
service/src/test/resources/ehr/mapper/non_consultation_bundles/contained-miscellaneous-records-bundle.json
service/src/test/resources/ehr/mapper/non_consultation_bundles/contained-unknown-resource-bundle.json
service/src/test/resources/ehr/mapper/non_consultation_bundles/expected-miscellaneous-records-output.xml
service/src/test/resources/ehr/mapper/non_consultation_bundles/observation-statement-stub.xml

Examples Allergy Intolerances referenced locally in a list could not be refenced in other components. Add support for referencing resources in the contained field of a list.  Referenced in the form:
*In list reference : #2e450b08-6b51-11ed-af8f-0a58a9feac02*
*Outside list: List/{ListID}#2e450b08-6b51-11ed-af8f-0a58a9feac02* 
- map all supported resources if they follow the *contained in list* referencing style  
- map resources referenced in a consultation to components in the consultation structure
- map resources that are only referenced locally in a list to the non-consultation structure

NIAD-2499: alternative list reference style

---

e2e-tests/src/test/java/uk/nhs/adaptors/gp2gp/e2e/EhrExtractTest.java
service/src/main/java/uk/nhs/adaptors/gp2gp/common/task/ProcessingErrorHandler.java

NACK codes below 10 should be prepended with a 0, i.e. 06

NIAD-2653: Bug Fix - NACK codes should be 2 digit strings

---

service/build.gradle
service/src/intTest/java/uk/nhs/adaptors/gp2gp/mhs/MhsWebClientTest.java
service/src/main/java/uk/nhs/adaptors/gp2gp/common/exception/MaximumExternalAttachmentsException.java
service/src/main/java/uk/nhs/adaptors/gp2gp/common/service/WebClientFilterService.java
service/src/main/java/uk/nhs/adaptors/gp2gp/common/task/ProcessingErrorHandler.java
service/src/main/java/uk/nhs/adaptors/gp2gp/common/task/TaskErrorHandler.java
service/src/main/java/uk/nhs/adaptors/gp2gp/common/task/TaskHandler.java
service/src/test/java/uk/nhs/adaptors/gp2gp/common/task/ProcessingErrorHandlerTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/common/task/TaskErrorHandlerTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/common/task/TaskHandlerTest.java

The MHS adaptor can limit the amount of external attachments. If the maximum value is hit the outbound service will respond with a http status of 400 and a plain text body describing the validation errors.   
According to the document *20151012_GP2GP 2.2 Spec clarifications.doc *:
>Where a sending system is unable to process an extract due to size of the record it must respond to the EHR_Request with an Application Acknowledgement with Response Code 30.
The adaptor is currently responding with response code 99.

NIAD-2726: BIG_FIX external attachments limit

---

README.md

Add an additional example to the README for the status endpoint when a migration is failed by the adaptor

NIAD-2767: Additional Status Endpoint Example

---

service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/StructuredRecordMappingService.java
service/src/main/java/uk/nhs/adaptors/gp2gp/mhs/model/OutboundMessage.java
service/src/test/java/uk/nhs/adaptors/gp2gp/gpc/StructuredRecordMappingServiceTest.java

This will allow us to store that field within the database, and use its value when chunking large attachments into chunks.

StructuredRecordMappingService populates a contentType field

---

service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcStructuredTaskExecutor.java
service/src/test/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcStructuredTaskExecutorTest.java

When checking for Attachments without a URL, the `GetGpcStructuredTaskExecutor` would insert two entries into the Documents array to be stored within the database.
Adds test to cover this behaviour, and removes duplicate code which generates the additional entry.

Fix duplicate entries within DocumentReferences array

---

README.md

In the section for "Using the helper script for Docker Compose" the filenames list for running locally are incorrect

Update README.md to correct incorrect filenames

---

service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrContinueTest.java
service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusTestUtils.java
service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrStatusConstants.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/SendDocumentTaskDefinition.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/SendDocumentTaskExecutor.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/request/EhrExtractRequestHandler.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/SendDocumentTaskExecutorTest.java

This value can then be used as an authoratitive value as opposed to pulling it out of the compiled MHS message.
In follow up work, the MHS message will contain application/octet-stream as this is what Spine requires, but isn't the actual content type which we still need.

NIAD-2812: Add document ContentType as provided by GP Connect to SendDocumentTaskDefinition

---

CHANGELOG.md
release/release.sh
release/version.sh

See commits messages for details.
- [Update release.sh to push a multi-architecture tag](https://github.com/nhsconnect/integration-adaptor-gp2gp/commit/6c07a2d3faf879cb94699417cbfe28f2129b819c)
- [Release version 1.5.10](https://github.com/nhsconnect/integration-adaptor-gp2gp/commit/f0e9122ce26c02d39e3ce56b17066afbdfa39c9c)
TODO: Create a release in GitHub against 4bfec38a68daa793e61066f9a81f5157830ab8d5

Create release 1.5.10

---

docker/wiremock/Dockerfile
docker/wiremock/stubs/__files/correctPatientStructuredRecordWithTextDocAttachment.json
docker/wiremock/stubs/__files/correctSimpleTextDocAttachment.json
docker/wiremock/stubs/mappings/retrieveCorrectPatientStructuredRecordWithSimpleDocAttachment.json
docker/wiremock/stubs/mappings/retrieveSimpleTextDocAttachment.json
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/SendDocumentTaskExecutor.java
service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/StructuredRecordMappingService.java
service/src/test/java/uk/nhs/adaptors/gp2gp/gpc/StructuredRecordMappingServiceTest.java

In the structured record mapping service, we have changed the outbound message which was always being created with a hardcoded value for `originalBase64` as `true`.  This flag appears to be ignored by EMIS, however it affected the import into TPP.
The following changes have been made:
* `originalBase64` will now be hardcoded to `false` when creating the outbound message in the structured record mapping service
* Unit Tests have been updated to reflect this change
* WireMock updated to assist in testing, with new responses created for this
When transferring a plain text file to TPP the text attachment was stored with the content encoded as Base64 even though the original attachment was not encoded.   In EMIS this attachment is displayed in plain text as expected.  This is not correct …

NIAD-2814: Fixed plain text file attachment being transferred into TPP as Base64Encoded

---

.github/pull_request_template.md

This adds a pull request template to be provided when a new pull request is opened
To ensure that pull requests are created with sufficient detail and to confirm that that required self checks have been completed

Add PR template to aid with code review

---

Jenkinsfile

Add 1hr timeout to pipeline
Pipeline currently has no timeout, which means that a technical fault can result in it needing to be manually cancelled.
A 1hr limit also ensures that we don't create a really slow pipeline, arguably 1hr is too long as well.

Add 1hr timeout to pipeline

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/common/amqp/JmsListenerErrorHandler.java

Guard against null pointer in JMS Error Handler.
A null pointer was encountered during testing of the PS Adaptor. This change introduces the prevention, as the implementation of the handler is the same for the GP2GP Adaptor.

guard against null pointer in JMS error handler

---

service/build.gradle
service/src/intTest/java/uk/nhs/adaptors/gp2gp/testcontainers/MongoDbContainer.java

Update TestContainers version to testcontainers:1.16.3
Update MongoDb version for test containers to mongo:3.6.23
Due to issues building and running integration tests on Apple M1 processor it has been required to update the test containers and MongoDb databases.
[Testcontainers for java 1.6.0 release information](https://github.com/testcontainers/testcontainers-java/releases/tag/1.16.0)

Update packages for TestContainers / MongoDb

---

CHANGELOG.md
docker/wiremock/stubs/__files/operationOutcomeNoRelationship.json
docker/wiremock/stubs/mappings/retrieveNackCodePatientNoRelationship.json
e2e-tests/src/test/java/uk/nhs/adaptors/gp2gp/e2e/EhrExtractTest.java
service/src/main/java/uk/nhs/adaptors/gp2gp/common/service/WebClientFilterService.java

Removed response type: NOT AUTHORISED (status 401)
Added response type: NO_RELATIONSHIP (status 403) to return error code 19
Refactor of WebClientFilterService to make easier to understand
If the losing practice ODS code doesn't match the ODS code for the patient’s registered practice on PDS, the GP Adaptor currently expects the GP Connect Provider to respond with a HTTP Status of 401 and an error code of NOT_AUTHORISED. However, as the GP Connect spec has been updated, it should expect a HTTP Status of 403 and an error code of NO_RELATIONSHIP, see the [GP Connect documentation](https://developer.nhs.uk/apis/gpconnect-1-6-0/accessrecord_structured_development_migrate_patient_record.html#error-handling).  
The adaptor should respond to this scenario with a negative acknowledgement …

NIAD-2799: Handle NO_RELATIONSHIP from GP Connect Provider

---

service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusServiceTest.java
service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrStatusConstants.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusService.java

As a subtask of NIAD-2290 (sender timeout) add a utility method to get in-progress transfers. 
The 8 day timeout only needs to check in-progress transfers. we do not currently have a method for this in the EhrExtractStatusService. 

NIAD-2944: Add utility method to get in-progress transfers

---

docker/service/Dockerfile

The focal image appears to be a suitable replacement as it is also based on Ubuntu 20.04
The adoptopenjdk images have been deprecated since 2021-08-01 in favour of eclipse-temurin.
This should bring in the latest security fixes.

Upgrade from jdk-11.0.11+9 to jdk-11.0.21+9

---

service/src/main/java/uk/nhs/adaptors/gp2gp/common/service/RequestBuilderService.java

REST buffers limits have been increased
REST buffer limits should be in line between different adaptors for consistent behaviour.

NIAD-2995: adjust buffer param

---

service/build.gradle

Having the latest version of Spring brings in the [latest security fixes](https://spring.io/blog/2023/11/16/spring-framework-5-3-31-and-6-0-14-available-now/).

Upgrade Spring from 5.3.23 to 5.3.31

---

.gitignore
mock-mhs-adaptor/build.gradle
mock-mhs-adaptor/lombok.config
service/build.gradle
service/lombok.config

1.18.22 adds support for Java 17
See: https://projectlombok.org/changelog
Version 6 of io.freefair.lombok does not generate the config file automatically.
Instead commit the generated version from 5.3.
See: https://github.com/freefair/gradle-plugins/issues/379

Upgrade lombok from 1.18.16 to 1.18.26

---

service/build.gradle

Package mentioned in description "hapi-fhir-structures-dstu3" has since been updated.
<details><pre>
+--- ca.uhn.hapi.fhir:hapi-fhir-structures-dstu3:5.4.0
|    +--- ca.uhn.hapi.fhir:hapi-fhir-base:5.4.0
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.12.3 -> 2.13.4.2 (*)
|    |    +--- org.apache.commons:commons-lang3:3.12.0
|    |    +--- org.apache.commons:commons-text:1.9 -> 1.10.0
|    |    |    \--- org.apache.commons:commons-lang3:3.12.0
|    |    +--- commons-codec:commons-codec:1.15
|    |    +--- commons-io:commons-io:2.8.0 -> 2.11.0
|    |    +--- com.google.guava:guava:30.1.1-jre
|    |    |    +--- com.google.guava:failureaccess:1.0.1
|    |    |    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    |    |    +--- …

Remove unnecessary dependency version pinning

---

docker/activemq/Dockerfile
docker/docker-compose-arm.yml
docker/docker-compose-transform-tool.yml
docker/docker-compose.yml

Update mongo image for docker-compose to use a specific version which works with ARM/AMD64
Update JDK Version
To make docker composes work with both architectures

Update Docker Composes to use compatible images

---

Jenkinsfile
developer-information.md
docker/e2e-tests/Dockerfile
docker/mock-mhs-adaptor/Dockerfile
docker/service/Dockerfile
e2e-tests/build.gradle
e2e-tests/src/test/java/uk/nhs/adaptors/gp2gp/e2e/EhrExtractTest.java
mock-mhs-adaptor/build.gradle
service/build.gradle

Upgrading to Java 17 allows us to upgrade to Spring Framework 6.1. We're currently on the latest version (5.3) which supports Java 11.

NIAD-3007: Upgrade from Java 11 to 17

---

docker/docker-compose-arm.yml

Activemq image changed to one that's working on m1 Macs.

Use same ActiveMQ image for M1 Macs as with x86 for consistency

---

docker/docker-compose.yml

This version has arm64 available, making performance on an M1 mac better.

Bump the version of the GP Connect Consumer adaptor used

---

service/build.gradle

[Version is managed by the gradle org.springframework.boot plugin](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#managing-dependencies.dependency-management-plugin).

Remove explicit versioning of spring dependencies

---

service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/GetAbsentAttachmentComponentTest.java
service/src/intTest/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcDocumentComponentTest.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusService.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/GetAbsentAttachmentTaskExecutor.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/model/EhrExtractStatus.java
service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcDocumentTaskExecutor.java

This way we can refer back to this value at a later date. We plan to use this when sending out the XML EhrExtract to populate the AbsentAttachment details.

NIAD-2394: Start storing the GP Connect document retrieval error message in Mongo

---

service/build.gradle
service/src/intTest/java/uk/nhs/adaptors/gp2gp/HealthCheckTest.java

Warning messages make finding actual errors harder.

Fix deprecation warnings

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/builder/GpcRequestBuilder.java

"SSP_FROM" header is removed when a request is made to GP Connect. 
The value of "SSP_FROM" header will be set in GP Connect by querying SDS service.

NIAD-2997: removal of unused ssp_from header

---

service/build.gradle

Versioning of reactor netty dependendency is already managed as part of the spring-boot-starter-webflux package, which is in turn versioned as part of Spring Framework version.
By having this explicit dependency we were downgrading the version of json-path in use.
This resolves a high CVE in json-smart

Remove json-path downgrade

---

service/build.gradle

The version we're using already has the specified version of commons-compress

Remove dependency override for testcontainers

---

service/build.gradle

This resolves an imcompatibility with Spring Framework 6

Upgrade Wiremock 2.27.2 -> 2.35.2

---

e2e-tests/build.gradle

These constraints are unnecessary, as Gradle is using 4.1.60 instead.
```
+--- io.netty:netty-handler:4.1.59.Final -> 4.1.60.Final (c)
\--- io.netty:netty-codec-http:4.1.59.Final -> 4.1.60.Final (c)
```

/e2e-tests Netty constraints are fulfilled by updated packages

---

service/build.gradle

This will reduce the dependencies we have to keep up to date, as Spring can maintain that.
We can instead focus on keeping Spring up to date and trust that they are patching logback-classic as and when required.
```
+--- org.springframework.boot:spring-boot-starter-logging:3.2.4
|    +--- ch.qos.logback:logback-classic:1.4.14
|    |    +--- ch.qos.logback:logback-core:1.4.14
|    |    \--- org.slf4j:slf4j-api:2.0.7 -> 2.0.12
```

Replace logback-classic dependency with spring-boot-starter-logging

---

service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusServiceTest.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusService.java
service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcStructuredTaskExecutor.java

Refactor updateEhrExtractStatusAccessDocumentDocumentReferences  in EHR Extract status service to pass in conversationId.
Currently it passes in an object and just extracts the conversationId from that.  It is simpler and easy to test if we just pass in the conversationId instead

Refactor updateEhrExtractStatusAccessDocumentDocumentReferences to pass in conversationId

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrDocumentMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/SendDocumentTaskExecutor.java
service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/DocumentToMHSTranslator.java
service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcStructuredTaskExecutor.java
service/src/test/java/uk/nhs/adaptors/gp2gp/gpc/EhrDocumentMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/utils/ResourceTestFileUtils.java

This makes calling the EhrDocumentMapper simpler, and consolidates the behaviour which was previously spread around into one class.

Simplify the EhrDocumentMapper to have one public method with two overloads

---

wiremock/README.md
wiremock/stubs/__files/correctPatientStructuredRecordResponse3AttachmentsWith2Absent.json
wiremock/stubs/mappings/migrateStructuredRecord_3AttachmentsWith2Absent.json
wiremock/stubs/mappings/retrievePatientStructuredRecord3Attachments2Missing.json

What
Add scenario for '3 Attachments with 2 Absent' to WireMock
Why
We need to test that all types of Absent Attachment are handled correctly and to be able to compare that they are all dealt with correctly. We have included attachment types where:
* The document reference points to a file which does not exist
* The document reference is missing a URL
* The document reference is a valid attachment
* Type of change
-[x] Internal change (non-breaking change with no effect on the functionality affecting end users)
Checklist:

Add the scenario for `3 Attachments with 2 Absent` to WireMock

---

wiremock/README.md
wiremock/stubs/__files/correctPatientStructuredRecordResponseAbsentAttachments.json
wiremock/stubs/mappings/migrateStructuredRecord_Absent Attachments.json

Scenarios for:
- When the content type isn't valid
- When the title field is populated
To help testing the adaptor within our PTL environment.

Add two more Absent Attachment scenarios to wiremock

---

service/src/intTest/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcDocumentComponentTest.java
service/src/main/java/uk/nhs/adaptors/gp2gp/common/service/WebClientFilterService.java
service/src/main/java/uk/nhs/adaptors/gp2gp/common/utils/OperationOutcomeIssueTypeDeserializer.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/GetAbsentAttachmentTaskExecutor.java
service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcDocumentTaskExecutor.java
service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/exception/GpConnectException.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/GetAbsentAttachmentTaskExecutorTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/GetGpcDocumentTaskExecutorTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/utils/OperationOutcomeIssueTypeDeserializerTest.java

Use the display message from the OperationOutcome when GP Connect error occurs, otherwise  use the default response: "The document could not be retrieved"
The error is message current returns a generic response without indicating what the error is, it is best to use the message from the operation outcome in the response if that is available.

Use the display message from OperationOutcome when GP Connect error occurs

---

service/build.gradle

Replace deprecated wiremock-jre8-standalone package with replacement

---

wiremock/README.md
wiremock/stubs/mappings/migrateStructuredRecord InternalServerError.json

Added mapping to WireMock which will allow us to test the retry-ability on our AWS environment by returning an Internal Server Error.

NIAD-3112 WireMock Internal Server Error

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/common/service/RandomIdGeneratorService.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/IdMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/common/service/RandomIdGeneratorServiceTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AllergyStructureMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/BloodPressureMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ConditionLinkSetMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DiaryPlanStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DocumentReferenceToNarrativeStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperComponentTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/IdMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ImmunizationObservationStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationToNarrativeStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/gpc/StructuredRecordMappingServiceTest.java

Updated the RandomIdGeneratorService and IdMapper to preserve UUIDs if a valid UUID is passed in.
Added additional testing for these services
Update unit tests to add mocking for the additional method within RandomIdGeneratorService
Currently the GP2GP Sending adaptor does not preserve the UUIDs for resources when mapping from Json to XML.  Valid GUID's should be preserved for resources where possible.

NIAD-3050: Preserve UUIDs when mapping

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/DiagnosticReportMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/SupportingInfoResourceExtractor.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/DiagnosticReportMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/utils/SupportingInfoResourceExtractorTest.java
service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-urn-oid-extension-id.json

Unit Tests added for SupportingInfoResourceAdaptor.
Updated SupportingInfoResourceAdaptor to handle NHS PMIP Report Numbers code systems prefixed with `urn:oid:`
Unit Test added for DiagnosticReportMapper
Updated DiagnosticReportMapper to handle NHS PMIP Report Numbers code systems prefixed with `urn:oid:`
Fixed `'Optional.get()' without 'isPresent()'` issues in SupportingInfoResourceExtractor.  Whereas previously this would throw an exception, the only place these methods are consumed are designed to handle an empty string being returned.  Have fixed this by returning an empty string if the resource is not found in the mapping context.
Fixed  `String concatenation as argument to 'StringBuilder.append()'` issues in SupportingInfoResourceExtractor by using StringBuilder correctly.
As the …

NIAD-3088: GP2GP adaptor should support OIDs

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AllergyStructureMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/AllergyStructureTemplateParameters.java
service/src/main/resources/templates/ehr_allergy_structure_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AllergyStructureMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperComponentTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/uat/EhrExtractUATTest.java

Update AllergyStructureMapper to add confidentialityCode based on the results of the ConfidentialityService when passed the resource.
Add tests for this functionality.
Update AllergyStructureTemplateParameters to include confidentialityCode. 
Update Moustache template for AllergyStructure to include confidentialityCode if present. 
Add Mocks for ConfidentialityCode to derived tests using the AllergyStructureMapper.
Address existing issues with checkstyle / spotbugs for modified files.
When an `AllergyIntolerance` resource contains a `meta.security` `NOPAT` value, as below:
```json
{
"meta": {
"security": [{
"system":"http://hl7.org/fhir/v3/ActCode",
"code":"NOPAT",
"display":"no disclosure to patient, family or caregivers without attending provider's authorization"
}]
}
}
```
Then the …

NIAD-3005: Handle NOPAT `Meta.Security` for `AllergyIntolerance`

---

service/build.gradle

`pitest-github` gradle task will fail by default if no mutation testing is performed.
This will occur when a PR is raised which doesn't change any production code. e.g. docs, tests only etc.

Don't fail Actions Workflow when no mutation testing is performed

---

CHANGELOG.md
service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrContinueTest.java
service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusServiceIT.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusService.java
service/src/main/java/uk/nhs/adaptors/gp2gp/mhs/InboundMessageHandler.java
service/src/main/java/uk/nhs/adaptors/gp2gp/mhs/exception/NonExistingInteractionIdException.java
service/src/main/java/uk/nhs/adaptors/gp2gp/mhs/exception/UnrecognisedInteractionIdException.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusServiceTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusServiceUnitTest.java

Setting the final ack for EhrExtract has been limited by a deadline of 8 days
There has been a deadline of 8 days set between receiving documents and the final ACK. If the deadline is exceeded the ACK will be ignored. 

Niad-2840: Identifies no acknowledgment after 8 Days

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ConditionLinkSetMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/ConditionLinkSetMapperParameters.java
service/src/main/resources/templates/ehr_link_set_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ConditionLinkSetMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperComponentTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/DiagnosticReportMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/SpecimenMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/uat/EhrExtractUATTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/utils/ConfidentialityCodeUtility.java
service/src/test/java/uk/nhs/adaptors/gp2gp/utils/XmlParsingUtility.java

Given a scenario where we receive a `Condition` with the `meta.security` value populated with `NOPAT`, then this PR contains the functionality to append the HL7v3 `confidentialityCode` to the `LinkSet` resource being mapped.
Please see the [ticket](https://nhse-dsic.atlassian.net/browse/NIAD-3147) for more information.

NIAD-3147 - Populate `confidentialityCode` HL7v3 element when `meta.security` with value `NOPAT` is present within `Condition`

---

service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/builder/GpcRequestBuilder.java

We don't explicitly depend on the Apache library, so switch to one we do.

Replace Apache HTTP Header imports with Spring HttpHeaders class

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ImmunizationObservationStatementMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/ImmunizationObservationStatementTemplateParameters.java
service/src/main/resources/templates/ehr_immunization_observation_statement_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ConditionLinkSetMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperComponentTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ImmunizationObservationStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/uat/EhrExtractUATTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/utils/XmlAssertion.java

* Add functionality for `confidentialityCode` to be include in mapped immunization, when the input contains `NOPAT` meta security tag.
* Add Unit Tests to `ImmunizationObservationStatementMapperTest` to test mapping of `confidentialityCode` when `NOPAT` Meta securityTag is present or not present
* Update `ImmunizationObservationStatementMapper` to inject ConfidentialityService and to add parameter for confidentiality service to `ImmunizationObservationStatementTemplateParameters`. 
* Update mustache template to include mapping for `confidentialityCode`.
* Update injection of ConfidentialityService in related test files. 
* Update CHANGELOG.md
A requirement for the Redactions work is to add NOPAT confidentialityCode handling to `Immunizations`:
_GP2GP Adaptor populates the …

NIAD-3149: Add confidentialityCode to Immunizations.

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/MedicationStatementTemplateParameters.java
service/src/main/resources/templates/ehr_medication_statement_authorise_template.mustache
service/src/main/resources/templates/ehr_medication_statement_prescribe_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperComponentTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/uat/EhrExtractUATTest.java

* Add functionality to provide `confidentialityCode` for both `PLAN` and `ORDER` when mapping `MedicationRequests` which contain a `NOPAT` `meta.security` tag. 
* Add Unit Tests to MedicationStatementMapperTest to test mapping of `confidentialityCode` when present or not present for both `supplyPrescribe` and `supplyAuthorise`.
* Update MedicationStatementMapper to inject ConfidentialityService and to add parameter for `confidentialityCode` to MedicationStatementTemplateParameters.
* Update mustache template to include mapping for confidentialityCode for both `PLAN` and `ORDER`. 
* Update injection of ConfidentialityService in related test files.
* Update CHANGELOG.md
A requirement for the Redactions work is to add NOPAT confidentialityCode handling to `MedicationRequests`:
_GP2GP Adaptor …

NIAD-3150: Add confidentialityCode to MedicationStatements.

---

service/src/intTest/resources/requestmessage/RCMR_IN010000UK05_payload.txt

This should reduce the amount of pointless logs being generated, as the size of the bundle is irrelevent to the correct execution of the E2E tests.
Taken from the Jenkins Artifacts for a build on main, and this PR.
Before:
```
uk.nhs.adaptors.gp2gp.ehr.NegativeAckHandlingTest.html	Sep 3, 2024 5:43:16 PM	14.27 MB
uk.nhs.adaptors.gp2gp.ehr.status.EhrStatusRequestsEndpointTests.html	Sep 3, 2024 5:43:17 PM	75.66 MB
```
After:
```
uk.nhs.adaptors.gp2gp.ehr.NegativeAckHandlingTest.html	Sep 3, 2024 6:34:01 PM	1.21 MB
uk.nhs.adaptors.gp2gp.ehr.status.EhrStatusRequestsEndpointTests.html	Sep 3, 2024 6:34:01 PM	5.62 MB
```

Switch patient used in E2E tests to be have a smaller Bundle returned

---

.github/workflows/build_workflow.yml
scripts/dump_docker_logs.sh

Due to ongoing challenges with Jenkins, we have initiated the migration to GitHub Actions as part of our strategy to enhance our CI/CD pipeline. This pull request introduces the initial GitHub Actions workflow, `build_workflow.yml`. This workflow is designed to replicate the stages defined in the existing `Jenkinsfile`, ensuring continuity and consistency in our build process.

NIAD-3173 - Add GitHub Action to replace current GP2GP Jenkins build

---

service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java

Add test for unsupported resource when mapping `Encounter`
This functionality was present but not tested.

NIAD-3137: Add test for unsupported resource when mapping `Encounter`

---

service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java

A quick refactor to use IsEqualToIgnoringWhitespace rather than helper method doing the same thing.
Code clarity and to remove unnecessary helper function

NIAD-3137: Refactor to use IsEqualToIgnoringWhitespace

---

README.md

Looks like the URL was changed at some point, which is fair given the previous URL appeared malformed.

README.md, fix broken link to API catalogue

---

README.md
nhs-england-developer-information.md

While it's important to keep our internal docs open source. They appear to be causing confusion to NMEs who are accidentally reading them.
Move the link to the developer-information.md to the bottom of the README.md

Reduce the risk of NMEs reading our internal guidance

---

service/src/intTest/resources/application.yml
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusService.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/scheduling/EhrExtractTimeoutScheduler.java
service/src/main/resources/application.yml
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusServiceTest.java

ehrExtractSentDaysLimit variable can be changed via application.yml file.
Customers can adjust the timeout duration by setting a value for EHR_EXTRACT_SENT_DAYS_LIMIT, which will then update the ehrExtractSentDaysLimit accordingly.

NIAD-2840: introducing a variable that can be changed via config file

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/DiagnosticReportMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/DiagnosticReportMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/utils/XmlAssertion.java
service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-effective-datetime-filing-comment.json
service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-effective-period-filing-comment.json
service/src/test/resources/ehr/mapper/diagnosticreport/fhir_bundle_with_filing_comments.json

This pull request introduces support for `confidentialityCode` within the `buildNarrativeStatementForObservationTimes` method in `DiagnosticReportMapper.java`.
More details can be found on the [ticket](https://nhse-dsic.atlassian.net/browse/NIAD-3144).

NIAD-3144-FIXES - Add `confidentialityCode` support for `Observation (Filing Comments)`

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java
service/src/test/resources/ehr/mapper/encountercomponents/expected-components-1.xml
service/src/test/resources/ehr/mapper/encountercomponents/expected-components-17-topic-no-categories.xml

* Update test files for EncounterComponentsMapperTest to now deal with cases where a virtual category is added for topics without a category. 
* Add functionality to EncounterComponentsMapper to now deal with cases where a virtual category is added for topics without a category. 
* Refactor EncounterComponentsMapper for readability. 
When attempting to transfer a patient containing a "flat" consultation (where there is a "TOPIC" but with no "CATEGORY") then EMIS reject the patient transfer as they _"expect all TOPIC's to contain a CATEGORY"_.
To avoid the transfer failing, we should create a "virtual" category to contain the resources when translating.

NIAD-3137: EMIS rejects flat consultation structure from GP2GP Adaptor

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/common/service/ConfidentialityService.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DocumentReferenceToNarrativeStatementMapperTest.java
service/src/test/resources/ehr/mapper/documentreference/example-document-reference-resource-with-nopat-security-label-16.json
service/src/test/resources/ehr/mapper/documentreference/example-document-reference-resource-with-nopat-security-label-17.json

NOPAT SecurityLabels and Meta Security has been added  to ReferredToExternalDocument
When securityLabel and meta security include NOPAT then confidentialityCode should be added to ReferredToExternalDocument section.

NIAD-3151: Adding NOPAT SecurityLabels and Meta Security to ReferredToExternalDocument

---

service/src/intTest/resources/application.yml
service/src/main/resources/application.yml

Removing EHR_EXTRACT_SENT_DAYS_LIMIT variable that is not used at the moment
At the moment EHR_EXTRACT_SENT_DAYS_LIMIT that is setup in application.yml is not used hence removing it for now

Removing a variable that is not used atm

---

mock-mhs-adaptor/src/main/java/uk/nhs/adaptors/mockmhsservice/configurations/AmqpConfiguration.java

Fix issues with deprecated `setBlackList` and `setWhiteList` and use `setAllowList` and `setDenyList` methods instead.

Fix issues with deprecated `setBlackList` and `setWhiteList` and use `setAllowList` and `setDenyList` methods instead.

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterMapperTest.java
service/src/test/resources/ehr/mapper/encounter/example-encounter-resource-14.json
service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-15.xml

Having done some testing with other GP2GP implementations we've identified that other systems will accept this and generate a fake placeholder Dr within their system when ingesting the record.
While the GP Connect spec insists that an Encounter has a participant of type REC, it is preferable to send a GP2GP extract than fail the transfer completely.

NIAD-3204: Allow sending an ehrComposition without an author/Participant2

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ConditionLinkSetMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ConditionLinkSetMapperTest.java
service/src/test/resources/ehr/mapper/condition/expected_output_linkset_21.xml

Having done some testing with other GP2GP implementations we've identified that other systems will accept this and optionally generate a fake placeholder Dr within their system when ingesting the record.
While the GP Connect spec insists that a Problem Header (Condition) has an asserter, it is preferable to send the GP2GP extract than fail the transfer completely.

NIAD-3211: Allow sending a `linkset` without a `Participant`

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapperTest.java
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-no-participant.xml

Having done some testing with other GP2GP implementations we've identified that other systems will accept this and optionally generate a fake placeholder Dr within their system when ingesting the record.
While the GP Connect spec insists that a MedicationRequest has a recorder, it is preferable to send the GP2GP extract than fail the transfer completely.

NIAD-3211: Allow sending a MedicationStatement without a Participant

---

service/src/test/resources/ehr/request/fhir/input/fhir-bundle-observations-after-diagnostic-report.json
service/src/test/resources/ehr/request/fhir/input/fhir-bundle-observations-before-diagnostic-report.json
service/src/test/resources/ehr/request/fhir/output/expected-xml-with-observations-inside-report.xml

These test resources aren't valid GP Connect filing comments because the "specimen" field is not a valid field for a filing comment.
The side effect of having the specimen field populated twice is that the expected XML was generating two NarrativeStatements with the text "This is some random free text".

Improve realism of Observation (Filing comment) tests

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapper.java

This method has a clear name describing what it does, and is documented.

Use common DiagnosticReport.isFilingComment in ObservationMapper

---

CHANGELOG.md
service/src/main/resources/templates/ehr_medication_statement_authorise_template.mustache
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-default-status-reason-code.xml
wiremock/stubs/__files/EMISPatientStructurede2eResponsePWTP3.json

When a MedicationRequest didn't have reason text to provide, we were providing an invalid code element within the pertinentSupplyInformation.
This is invalid according to the spec.
Instead, move the nullFlavor annotation to the pertinentSupplyAnnotation where it is valid.

NIAD-3218: Fix malformed ehrSupplyDiscontinue / pertinentInformation / pertinentSupplyAnnotation

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/StatementTimeMappingUtils.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/utils/StatementTimeMappingUtilsTest.java

* Improve exception message detailing the reason for the failure and the ID of the resource causing the exception. 
* Add unit tests for the `prepareAvailabilityTimeForMedicationRequest` and `prepareEffectiveTimeForMedicationRequest` methods as none previously existed.
During testing it was difficult to ascertain which resource had caused the exception, or the reasoning behind the failure.  This should make it easier to find and identify the cause of the issue.
- [x ] I have performed a self-review of my code
- [-] My changes generate no new warnings
- [-] I have updated the [Changelog](CHANGELOG.md) with details of my change in the UNRELEASED section if this change will affect end users

Improve exception messages when mapping MedicationRequest `AvailabilityTime` and `EffectiveTime` fields

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationValueQuantityMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationValueQuantityMapperTest.java

Add functionality to XML escape the `code` and `unit` when generating the XML string. `value` does not need to be escaped as it is a `BigDecimal` type. Add unit tests to test above functionality.
To avoid the possibility of XML Injection, and to ensure that any generated XML is formatted correctly, all input from the GP Connect Bundle should be XML escaped when mapping `Observation` valueQuantities.
For example, if the input bundle contains the following valueQuantity:
```json
"valueQuantity": {
"value": 186,
"unit": "<None>",
"system": "http://unitsofmeasure.org"
}
```
Then the resultant `<value>` element should contain the XML Escaped value for `unit`:
```xml
<value xsi:type="PQ" value="186" unit="1">
<translation value="186">
<originalText>&lt;None&gt;</originalText>
</translation> …
```

NIAD-3227: When mapping `Observation` valueQuantities, any input from the GP Connect Bundle should be escaped

---

service/build.gradle

Configure Gradle to automate the deletion of older summaries on Github Pull Requests
When committing to a branch which has an open PR, the mutation testing will rerun and generate a new summary, leaving the old summary in place, which is no longer relevant.  This then had to be manually deleted or remain as clutter.  This change configures the plugin to delete old summaries.

Configure Gradle to automate the deletion of older summaries on Github Pull Requests

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapperTest.java
service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_test_group_header.json

* Replace String.Empty when preparing the code element mapping ObservationMapper so that an EhrMapperException is thrown containing the resource identifier. 
* Add test to ensure this exception is found and contains the resource ID.
* Update NOPAT test and associated resource file which previously did not contain a code element 
* Update CHANGELOG.md
Within the `diagnosticreport.ObservationMapper::prepareCodeElement` there is the possibility of generating an EMPTY code element:
```java
private String prepareCodeElement(Observation observation) {
if (observation.hasCode()) {
return codeableConceptCdMapper.mapCodeableConceptToCd(observation.getCode());
}
return StringUtils.EMPTY;
}
```
This results in a `CompoundStatement` without a code element, which is invalid, and will cause the …

NIAD-3222: GP2GP adaptor generates an empty `CompoundStatement/code` which fails the transfer.

---

wiremock/stubs/__files/correctPatientStructuredRecordLargePayload.json

Helps testing NOPAT functionality with Incumbents

Add NOPAT security to AllergyIntolerance in Wiremock stub

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/request/EhrExtractRequestHandler.java
service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcStructuredTaskDefinition.java

introduction of a factory method to create instances of GetGpcStructuredTaskDefinition class
Moving a functionality of GetGpcStructuredTaskDefinition instances creation into a better place

NIAD-3234: introduction of a factory method to create instances of GetGpcStructuredTaskDefinition class

---

mock-mhs-adaptor/src/main/java/uk/nhs/adaptors/mockmhsservice/service/MockMhsService.java

Code Quality fix for non-constant string concatenation when logging in `MockMhsService`
Non-constant concatenations are evaluated at runtime even when the logging message is not logged; this can negatively impact performance. It is recommended to use a parameterised log message instead, which will not be evaluated when logging is disabled

Code Quality: Non-constant string concatenation as argument to logging call

---

wiremock/src/main/java/PatientDemographicsServiceClient.java

* Code Quality fix to replace deprecated constructors on `URL(java.lang.String) with the recommended `URI().toURL()` method instead 
* Fix warning with Unchecked assignment: 'java.util.HashMap' to 'java.util.Map<java.lang.String,java.lang.Object>'"
[Deprecate URL public constructors](https://bugs.openjdk.org/browse/JDK-8294241)
Warning: Unchecked assignment: 'java.util.HashMap' to 'java.util.Map<java.lang.String,java.lang.Object>'

Code Quality: Replace deprecated constructor call and fix unchecked assignment warning

---

service/src/main/java/uk/nhs/adaptors/gp2gp/common/service/FhirParseService.java
service/src/test/java/uk/nhs/adaptors/gp2gp/common/service/FhirParseServiceTest.java

Enforcing strict error handling while converting json tests
JSON converter in FhirParseService can convert objects in strict error handler mode or non-strict. In GP2GP adaptor we use the strict mode hence adding tests to confirm that. 

Enforcing strict error handling while converting json tests

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrResendController.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/EhrResendControllerTest.java

When an error happens on the adaptor when fetching the Structured Record, the EHR error field will be populated.
Clear this, as otherwise the ProcessFailureHandlingService.hasProcessFailed check will return true.

Also clear the ehrExtractStatus.error field before resending EHR

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrResendController.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/EhrResendControllerTest.java

A resend log message was updated
A resend log message was updated to be more clear and descriptive

NIAD-3234: updating a log message to be more clear

---

README.md
gp2gp_adaptor_response_docs.yaml

Endpoints documentation update
The documentation must remain synchronized with the code implementation to ensure accuracy, clarity, and ease of use. This alignment minimizes confusion, reduces the risk of errors during integration, and provides developers with reliable information to effectively utilize the API.

NIAD-3234: endpoint docs update

---

OPERATING.md
README.md

Clarify that GP2GP_SERVER_PORT is for the API specifically.
Fix broken link in the "Table of contents" to the API information.
Link out to the editor.swagger.io interface which is a bit nicer for viewing the spec.

Improve the API documentation

---

CHANGELOG.md
OPERATING.md
service/src/intTest/resources/application.yml
service/src/main/resources/application.yml

Retain failed transfers for 12 weeks / 84 days as per spec.
Required by specifications. Facilitates data retention and the ability to initiate a retry.

Retain failed transfers for 12 weeks / 84 days

---

.github/workflows/build_workflow.yml
.github/workflows/mutationtesting.yml

* Add an if condition to the mutation testing GitHub action to prevent the mutation testing from being run if the GitHub actor is dependabot.
* Add a conditional job for the build workflow to not generate a sonar report when triggered by dependabot.
Currently the mutation testing workflow triggers when dependabot raises a PR, and generating the Sonar report also fails in the unit tests stage of the build action.
These fail as Dependabot does not have access to GitHub secrets.

Prevent Sonar Reports and Mutation Testing running when triggered by Dependabot

---

service/build.gradle
service/src/main/java/uk/nhs/adaptors/gp2gp/common/configuration/AppInitializer.java
service/src/main/java/uk/nhs/adaptors/gp2gp/common/configuration/CustomTrustStore.java
service/src/main/java/uk/nhs/adaptors/gp2gp/common/storage/StorageConnectorConfiguration.java
service/src/test/java/uk/nhs/adaptors/gp2gp/common/configuration/AppInitializerTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/common/configuration/CustomTrustStoreTest.java

NIAD-3208: CustomTrustStore refactoring to exclude weird dependencies

---

CHANGELOG.md
service/src/main/resources/templates/ehr_medication_statement_authorise_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapperTest.java
service/src/test/resources/ehr/mapper/medication_request/medication-request-special-character-in-code.json
service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-xml-escaped-text-values.xml

* Update template used when mapping `MedicationStatements` to XML escape any user provided text field,
* Add test for user provided text fields when mapping `MedicationRequest` to `MedicationStatement`.
* Add XML / JSON for the above tests.
When sending an outbound GP2GP Request, the request would fail if the provided `medicationStatement.extension.extension.valueCodeableConcept.text` contained special characters as these were not being escaped when mapping to `ehrSupplyDiscontinue / pertinentInformation / pertinentSupplyAnnotation / text`.

XML Escape text fields when mapping to `MedicationStatement`

---

service/src/main/java/uk/nhs/adaptors/gp2gp/common/service/ConfidentialityService.java
service/src/test/java/uk/nhs/adaptors/gp2gp/common/service/ConfidentialityServiceTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AllergyStructureMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/utils/ConfidentialityCodeUtility.java

SystmOne are opinionated about this.
Confidentiality code format fix
TPP advised us that that there should be no new line between 'confidentiality code' tag and the next tag

Remove new lines from ConfidentialityCode tag

---

service/src/main/resources/templates/ehr_allergy_structure_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AllergyStructureMapperTest.java

Incumbents don't appear to be accepting the confidentialityCode as it is currently on the CompoundStatement.

AllergyMapper: Add confidentialityCode to ObservationStatement

---

wiremock/stubs/__files/correctPatientStructuredRecordResponseAbsentAttachments.json

There are two ways a DocumentReference can be given a NOPAT marking according to the GP2GP spec, this PR introduces examples for both.
This will allow us to more easily test the behaviour of incumbent systems E2E.

Add NOPAT to DocumentReference Wiremock stubs

---

wiremock/stubs/__files/EMISPatientStructurede2eResponsePWTP9.json

Current specimen is part of the same investigation which has a comment note with NOPAT.
By moving the specimen with NOPAT to a separate investigation we help make the testing simpler.

Wiremock Investigations: Move NOPAT between Specimens

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementExtractor.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapperTest.java
service/src/test/resources/ehr/mapper/medication_request/mr-plan-with-unrecognised-uncoded-prescription-type.json

* Add exception for the case where prescription type is unrecognised (the text value is present but is not "No information available").
* Add unit test and test file for the above change.
* Remove now unused methods and constants from `MedicationStatementExtractor`.
Ensure compliance in response to [GP Connect 1.6.2 Changelog](https://simplifier.net/guide/gp-connect-access-record-structured/Home/Introduction/Release-notes?version=current#1.6.2)

Add exception for unrecognised and uncoded prescription types

---

wiremock/stubs/__files/correctPatientStructuredRecordLargePayload.json

Conditions with NOPAT added to them:
- ImmunisationsProblem - No ActualProblem extension
- Problem-A-Anxiety-With-Depression - An ActualProblem related to Observation/Consultation1-Topic1-Category-History-Observation-2
- MedicationProblem - No ActualProblem extension
Swollen Legs condition remains without any Security labelling.
To help test the adaptor E2E with incumbents

Add NOPAT to Conditions within the "Large Patient Record" Wiremock scenario

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/CodeSystemsUtil.java
service/src/test/java/uk/nhs/adaptors/gp2gp/utils/CodeSystemUtilTest.java

*  Add CodeSystemUtil to map from JSON FHIR codes (urls) to HL7 XML codes (OIDs).
*  Add functionality to ensure that the JSON FHIR Code is preserved when the JSON FHIR Code is not a known code system.
* Add unit tests for the above functionality.
When implementing the changes required in NIAD-3304, when mapping a codeable concept we will no longer only be mapping SNOMEDCT codes, but will also need to preserve codes from other codes systems.  When completing this part of the work for the GP2GP Request adaptor, a number of code types were identified as known codes.
These FHIR code systems and corresponding HL7 OIDs are listed below:
* `http://snomed.info/sct` -> `2.16.840.1.113883.2.1.3.2.4.15`
* `https://fhir.hl7.org.uk/Id/egton-codes` -> `2.16.840.1.113883.2.1.6.3`
* …

NIAD-3304: Add CodeSystemUtil for mapping between code systems

---

service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapperTest.java
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_with_both_description_extensions_no_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_with_both_description_extensions_no_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_with_only_descriptionId_extension_no_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_with_only_descriptionId_extension_no_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_with_only_descriptionId_extension_with_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_with_only_descriptionId_extension_with_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_without_extensions_no_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_without_extensions_no_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_without_extensions_with_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_without_extensions_with_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_without_snomed_code_in_coding_no_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_without_snomed_code_in_coding_no_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_without_snomed_code_in_coding_with_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_without_snomed_code_in_coding_with_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyClinicalStatus/codeable_concept_with_allergy.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_with_both_description_extensions_no_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_with_both_description_extensions_no_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_with_only_descriptionId_extension_no_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_with_only_descriptionId_extension_no_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_without_extensions_no_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_without_extensions_no_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_without_extensions_with_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_without_extensions_with_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_without_snomed_code_in_coding_no_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_without_snomed_code_in_coding_no_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_without_snomed_code_in_coding_with_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_without_snomed_code_in_coding_with_text.xml

* Add unit tests for mapping allergy codeable concepts.
No unit tests were present, and changes are required to be made to the code.

Add unit tests for mapping allergy codeable concepts

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapperTest.java
service/src/test/resources/ehr/mapper/medication_request/fhir-bundle.json
service/src/test/resources/ehr/mapper/medication_request/mr-referencing-medication-with-no-snomed-code.json
service/src/test/resources/ehr/mapper/medication_request/mr-referencing-medication-with-non-snomed-codes.json
service/src/test/resources/ehr/mapper/medication_request/ms-with-material-coding-containing-null-flavor-code.xml
service/src/test/resources/ehr/mapper/medication_request/ms-with-material-coding-containing-translations.xml

* Update `fhir-bundle.json` to add `Medication` resources for non-snomed codes, and additionally for when no SNOMED code is present.
* Add test to ensure that translations are added when a `Medication` contains a snomed code and non-snomed codes.
* Add test to ensure that a `nullFlavor="UNK"` coding block is created when no snomed codes are present in a `Medication`.
* Add test files for the above tests.
The GP2GP Sending Adaptor does not currently preserve non-SNOMEDCT codes when mapping CodeableConcepts.
The GP2GP Request Adaptor does preserve this codes when a SNOMEDCT code is also present in the coding block.
It is necessary as part of FRA that these are preserved when transferring a patient out of NME system.
This is the first part of the …

NIAD-3304: Add functionality for medication codeable concepts to include non-SNOMEDCT codes

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapperTest.java
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_with_snomed_and_non_snomed_codes_in_coding_no_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_with_snomed_and_non_snomed_codes_in_coding_no_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_with_snomed_and_non_snomed_codes_in_coding_with_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_with_snomed_and_non_snomed_codes_in_coding_with_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_with_snomed_and_non_snomed_codes_in_coding_no_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_with_snomed_and_non_snomed_codes_in_coding_no_text.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_with_snomed_and_non_snomed_codes_in_coding_with_text.json
service/src/test/resources/ehr/mapper/codeableconcept/allergyResolved/allergy_with_snomed_and_non_snomed_codes_in_coding_with_text.xml

* Add test files for `active` and `resolved` allergies where both snomed and non-snomed codes are provided, with and without text field provided.
* Update `mapCodeableConceptToCdForAllergy` to provide translations in cases where the code is no an `UNK` null flavour.
The GP2GP Sending Adaptor does not currently preserve non-SNOMEDCT codes when mapping CodeableConcepts.
The GP2GP Request Adaptor does preserve this codes when a SNOMEDCT code is also present in the coding block.
It is necessary as part of FRA that these are preserved when transferring a patient out of NME system.

NIAD-3304: GP2GP Sending Adaptor not preserving legacy codes when mapping allergies

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DiaryPlanStatementMapper.java
service/src/main/resources/templates/ehr_plan_statement_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DiaryPlanStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperComponentTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/uat/EhrExtractUATTest.java
service/src/test/resources/ehr/mapper/procedurerequest/procedure-request-resource-1.json

Send over ProcedureRequest.meta.security NOPAT field to incumbent
This change is part of a broader scope of work aimed at ensuring the GP2GP sending adapter complies with Redactions requirements

NIAD-3152: Send over ProcedureRequest.meta.security NOPAT field to incumbent

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapperTest.java

* Add tests for existing functionality when mapping `CodeableConcept` for blood pressures.
* Slight refactor on `CodeableConceptCdMapper` for readability and allow testing around existing bug when retrieving the original text value from the display extension.
This method was untested and changes are required when handling non-SNOMEDCT codes.

NIAD-3304: Adaptor not preserving legacy read codes on export

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapperTest.java
service/src/test/resources/ehr/mapper/blood_pressure/blood-pressure-with-codeable-concepts.xml

* Add functionality when mapping blood pressures to preserve non snomed codes 
* Add tests to handle non snomed code translations
The GP2GP Sending Adaptor does not currently preserve non-SNOMEDCT codes when mapping CodeableConcepts.
The GP2GP Request Adaptor does preserve this codes when a SNOMEDCT code is also present in the coding block.
It is necessary as part of FRA that these are preserved when transferring a patient out of NME system.

GP2GP Sending Adaptor not preserving legacy read codes on export for blood pressures

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/RequestStatementTemplateParameters.java
service/src/main/resources/templates/ehr_request_statement_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperComponentTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/uat/EhrExtractUATTest.java
service/src/test/resources/ehr/mapper/referral/example-referral-request-with-nopat.json

Adding confidentialityCode to RequestStatement
When the ReferralRequest.meta.security field contains NOPAT and the message type is RCMR_IN030000UK07, the GP2GP Adaptor will now populate the RequestStatement / confidentialityCode field accordingly.

NIAD-3153: Adding confidentialityCode to RequestStatement

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/BloodPressureMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/BloodPressureParameters.java
service/src/main/resources/templates/ehr_compound_statement_blood_pressure_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/BloodPressureMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperComponentTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/uat/EhrExtractUATTest.java
service/src/test/resources/ehr/mapper/blood_pressure/blood-pressure-with-nopat.json
service/src/test/resources/ehr/mapper/blood_pressure/blood-pressure-with-nopat.xml

The GP2GP Adaptor now populates the CompoundStatement / confidentialityCode field when Observation.meta.security field contains NOPAT
The GP2GP Adaptor now populates the CompoundStatement / confidentialityCode field when Observation.meta.security field contains NOPAT

NIAD-3154: CompoundStatement confidentialityCode field is populated when Observation.meta.security field contains NOPAT

---

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/CodeSystemsUtil.java
service/src/main/resources/templates/codeable_concept_cd_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/utils/CodeSystemUtilTest.java
service/src/test/resources/ehr/mapper/blood_pressure/blood-pressure-with-codeable-concepts.xml
service/src/test/resources/ehr/mapper/codeableconcept/allergyActive/allergy_with_snomed_and_non_snomed_codes_in_coding_with_text.xml
wiremock/stubs/__files/EMISPatientStructurede2eResponsePWTP3.json

* Update CD template to ensure that `originalText` is always populated first.
* Update tests to reflect the ordering change
* Update `CodeableConceptCdMapper` to only add code translations when it is possible to map from URL to OID as anything other than an OID is not supported in the schema.
* Update CodesSystemsUtil to return empty string if a mapping to known code system cannot be found.
* Update test accordingly.
* Update `CodeableConceptCdMapper` to create a new coding element for legacy codes, to avoid modifying an element whilst iterating a list.
* Add test for an unknown code system.
* SonarCube fix to remove public modifier on test class.
* Fix error in "Medications" test file, where a legacy code contains a space, which is not valid according to the schema.
The imports were …

NIAD-3304: Ensure correct ordering of `originalText` when mapping `CodeableConcept` to `CD`

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/BloodPressureMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/BloodPressureParameters.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/RequestStatementTemplateParameters.java
service/src/main/resources/templates/ehr_compound_statement_blood_pressure_template.mustache
service/src/main/resources/templates/ehr_request_statement_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/BloodPressureMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapperTest.java

Putting the reverted changes for NIAD-3153 and NIAD-3154 back in place
The reverted changes were just temporarily removed to make the next release to come through and now the original changes are being put back into their place

NIAD-3153, -3154: putting the reverted changes for NIAD-3153 and NIAD-3154 back in place

---

service/src/main/java/uk/nhs/adaptors/gp2gp/common/service/XPathService.java
service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/StructuredRecordMappingService.java

* Update from `.newInstance()` to `.newDefaultInstance()` on `DocumentBuilderFactory` and `TransformerFactory` which should add the flags for critical security risks.

Code Improvement: Disable access to external entities in XML parsing.

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/EncounterTemplateParameters.java
service/src/main/resources/templates/ehr_encounter_to_ehr_composition_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperComponentTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/uat/EhrExtractUATTest.java
service/src/test/resources/ehr/mapper/encounter/input-encounter-with-nopat.json
service/src/test/resources/ehr/mapper/encounter/output-with-confidentiality-code.xml

Send over Encounter.meta.security NOPAT field to incumbent
Making Encounter resource compliant with Redactions changes

NIAD-3156: Send over Encounter.meta.security NOPAT field to incumbent

---

CHANGELOG.md
service/build.gradle
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationStatementMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/ObservationStatementTemplateParameters.java
service/src/main/resources/templates/unstructured_observation_statement_template.mustache
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperComponentTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/uat/EhrExtractUATTest.java
service/src/test/resources/ehr/mapper/observation/example-observation-resource-with-nopat.json
service/src/test/resources/ehr/mapper/observation/expected-observation-statement-with-confidentiality-code.xml

Send over Observation (uncategorised data).meta.security NOPAT field to incumbent
Making Observation (uncategorised data) compliant with Redactions

NIAD-3157: Send over uncategorised data observation NOPAT field to incumbent

---

CHANGELOG.md
service/build.gradle
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapper.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapperTest.java
service/src/test/resources/ehr/mapper/referral/example-referral-request-with-ubr-number-system-url.json
service/src/test/resources/ehr/mapper/referral/example-referral-request-with-ubrn-system-url.json
service/src/test/resources/ehr/mapper/referral/expected-output-request-for-system-url.xml

RequestStatementMapper is currently filtering for e-referrals by checking for any ReferralRequest using an identifier url of `https://fhir.nhs.uk/Id/ubr-number`.
Therefore we have updated this adaptor to be able to filter for both types of url when filtering to ensure that we can accept both the new url and the older one for systems which are still using it.
The ERS (E-Referral Service) programme have chosen to use https://fhir.nhs.uk/Id/UBRN.
- [X ] New feature (non-breaking change which adds functionality)

NIAD-3294 - Allow RequestStatementMapper to handle updated UBRN system URL

---

CHANGELOG.md
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapper.java
service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/SupportingInfoResourceExtractor.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapperTest.java
service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapperTest.java
service/src/test/resources/ehr/mapper/medication_request/mr-with-order-no-optional-fields-with-medication-codeable-concept.json
service/src/test/resources/ehr/mapper/referral/example-referral-request-supportingInfo-medication-request-with-medication-codeable-concept.json
service/src/test/resources/ehr/mapper/referral/expected-output-request-statement-supportingInfo-from-medication-codeable-concept-display.xml
service/src/test/resources/ehr/mapper/referral/fhir-bundle.json

* Add test and test file where the `MedicationRequest` contains a `medicationCodableConcept` and not a `medication.reference` to ensure that this is used if it is provided.
* Update `MedicationStatementMapper` to implement this.
* Add test and test file where 'SupportingInfo` is generated from a medication request and the referenced `MedicationRequest` contains a `medicationCodableConcept` and not a `medication.reference` to ensure that this is used if it is provided.
* Update the `fhir-bundle.json` test file to add new MedicationRequest with a `medicationCodeableConcept`
* Ensure existing tests still pass using the original functionality
MedicationRequest and MedicationStatement profiles have had the constraint on the medication element relaxed so they align with the base profile i.e. …

NIAD-3301: Update MedicationRequest.medication datatype support.
