README.md, docker/docker-compose.yml, service/build.gradle, service/src/main/java/uk/nhs/adaptors/gp2gp/TestClass.java, service/src/main/java/uk/nhs/adaptors/gp2gp/configuration/MongoClientConfiguration.java, service/src/main/java/uk/nhs/adaptors/gp2gp/model/EhrExtractStatus.java, service/src/main/java/uk/nhs/adaptors/gp2gp/repository/EhrExtractStatusRepository.java, service/src/main/resources/application.yml
Added configuration and repository. As requested changed "id" in EhrExtractStatus collection to "extractId".
=> Implemented mongo db connection and repository

Jenkinsfile
Deploy to cluster1 and run E2E tests afterwards. Use lock to prevent parallel runs.
=> NIAD-805 Pipeline: Deploy GP2GP adaptor to build1 cluster

docker/wiremock/stubs/__files/correctSDSResponse.json, docker/wiremock/stubs/__files/notFoundSDSResponse.json, docker/wiremock/stubs/mappings/retrieveNoneExisitingSDSRecord.json, docker/wiremock/stubs/mappings/retrieveSDSRecord.json
Usage and testing notes were added in the comment of the story NIAD-783.
=> NIAD-783: Add SDS api responses to mock

service/src/intTest/java/uk/nhs/adaptors/gp2gp/HealthCheckTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/common/amqp/MessageQueueTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/common/mongo/ttl/TimeToLiveTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/common/storage/StorageConnectorTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/common/task/BaseTaskTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusRepositoryTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/SendEhrExtractCoreComponentTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcDocumentComponentTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcDocumentReferencesComponentTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcStructuredComponentTest.java
This reverts commit 682b09d6f5c3366b238903a30fe393c841e85570.
=> Revert "Remove @DirtiesContext annotation to reduce build times (#68)"

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/SendEhrContinueTaskExecutor.java
fix log message, remove double extension.
=> NIAD-874: Fix log message

Jenkinsfile, docker/docker-compose-e2e-tests.yml
change vars from pub to local for wiremock
=> NIAD-1076: Pipeline to run against wiremock

README.md, docker/docker-compose.yml, service/src/intTest/resources/application.yml, service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/builder/GpcRequestBuilder.java, service/src/main/resources/application.yml
add override nhs number env var + updated readme
=> NIAD-1073: Force specific nhs number for test with env var

service/src/main/resources/templates/ehr_agent_template.mustache, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/OrganizationToAgentMapperTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/utils/TestArgumentsLoaderUtil.java, service/src/test/resources/ehr/mapper/organization/organization_with_no_optionals.json, service/src/test/resources/ehr/mapper/organization/organization_with_no_optionals.xml, service/src/test/resources/ehr/mapper/organization/organization_with_use_old.json, service/src/test/resources/ehr/mapper/organization/organization_with_use_old.xml
=> NIAD-908: organization to agent testing feedback

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/DateFormatUtil.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/utils/AllergyStructureExtractorTest.java, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-1.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-2.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-3.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-4.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-5.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-7.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-8.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-9.xml
change dateutil format plus fix allergy intolerance tests
=> NIAD-1082: Refactor dateutil format

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/IdMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ImmunizationObservationStatementMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/ImmunizationObservationStatementTemplateParameters.java, service/src/main/resources/templates/immunization_observation_statement_template.mustache, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ImmunizationObservationStatementMapperTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/uat/EhrExtractUATTest.java, service/src/test/resources/ehr/mapper/encountercomponents/expected-components-1.xml, service/src/test/resources/ehr/mapper/immunization/expected-output-observation-statement-all-information.xml, service/src/test/resources/ehr/mapper/immunization/expected-output-observation-statement-no-date.xml, service/src/test/resources/ehr/mapper/immunization/expected-output-observation-statement-no-information.xml, service/src/test/resources/ehr/mapper/immunization/expected-output-observation-statement-reason-not-given.xml, service/src/test/resources/ehr/mapper/immunization/expected-output-observation-statement-with-context.xml, service/src/test/resources/ehr/mapper/immunization/expected-output-observation-statement-without-participant.xml, service/src/test/resources/ehr/mapper/immunization/expected-output-observation-with-vaccine-code.xml, service/src/test/resources/ehr/mapper/immunization/immunization-no-practitioner.json, service/src/test/resources/ehr/mapper/immunization/immunization-practitioner-but-no-actor.json
https://gpitbjss.atlassian.net/browse/NIAD-1096
AC3 - add Participant element to ObservationStatement
GIVEN Immunization is translated to ObservationStatement
THEN Practitioner element is added to ObservationStatement
AND Practitioner is referencing Agent
=> NIAD-1096: Add participant element when translating Immunization to ObservationStatement

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapper.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapperTest.java, service/src/test/resources/ehr/mapper/referral/example-referral-request-resource-20.json
Request statements can be made by practitioners without any reference to an organisation on whose behalf it was made.
=> NIAD-1312: Allow request from practitioners on behalf of no organisation

service/src/main/resources/templates/ehr_encounter_to_ehr_composition_template.mustache, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-1.xml, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-10.xml, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-11.xml, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-12.xml, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-13.xml, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-2.xml, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-3.xml, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-4.xml, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-5.xml, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-6.xml, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-7.xml, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-8.xml, service/src/test/resources/ehr/mapper/encounter/expected-output-encounter-9.xml, service/src/test/resources/ehr/request/fhir/output/ExpectedEhrExtractResponseFromJson.xml, service/src/test/resources/uat/output/TC4-9465701610_Powne_cons1only_20210212.xml
#160 added Participant2 with typeCode of "RESP", but it should have been "PPRF".
=> NIAD-1318: Change Participant2 typeCode from RESP to PPRF

service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapperTest.java, service/src/test/resources/ehr/mapper/referral/example-referral-request-resource-21.json, service/src/test/resources/ehr/mapper/referral/expected-output-request-statement-15.xml, service/src/test/resources/ehr/mapper/referral/fhir-bundle.json
Added additional test for multiple recipients
=> NIAD-1314: Added additional test for Request Mapper

service/src/main/resources/templates/ehr_compound_statement_blood_pressure_template.mustache, service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-with-data.xml, service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-with-diastolic-data-only.xml, service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-with-period-date.xml, service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-with-systolic-data-only.xml, service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-without-effective-date.xml, service/src/test/resources/ehr/mapper/blood_pressure/blood-pressure-with-codeable-concepts.xml, service/src/test/resources/ehr/mapper/blood_pressure/blood-pressure-with-data-nested.xml, service/src/test/resources/ehr/mapper/blood_pressure/blood-pressure-with-data.xml, service/src/test/resources/ehr/request/fhir/output/expected-ehr-extract-response-from-json.xml, service/src/test/resources/uat/output/TC4-9465699926_Sajal_full_20210122.xml, service/src/test/resources/uat/output/TC4-9465700339_Yamura_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701297_Livermore_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701459_Nel_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701483_Dougill_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701483_Nel_full_20210119.xml
* Removed valueQuantity tag from blood pressure template
* Updated test resource files accordingly
=> NIAD-1425: Blood pressure removed valueQuantity element

service/src/main/resources/templates/ehr_allergy_structure_template.mustache, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-1.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-10.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-11.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-12.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-13.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-14.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-2.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-3.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-4.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-5.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-6.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-7.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-8.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-9.xml, service/src/test/resources/ehr/mapper/encountercomponents/expected-components-1.xml, service/src/test/resources/ehr/request/fhir/output/ExpectedResponseFrom1ConsultationResponse.xml, service/src/test/resources/ehr/request/fhir/output/expected-ehr-extract-response-from-json.xml, service/src/test/resources/ehr/request/fhir/output/expected-xml-without-effective-time.xml, service/src/test/resources/uat/output/TC4-9465698490_Daniels_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465698679_Gainsford_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465699918_Magre_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465699926_Sajal_full_20210122.xml, service/src/test/resources/uat/output/TC4-9465700193_Birdi_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465700339_Yamura_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701297_Livermore_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701459_Nel_full_20210119.xml
* Removed hardcoded contextConductionInd=true from AllergyStructure template
* Updated test resource files accordingly
=> NIAD-1428: Allergy Structure removed contextConductionInd

service/src/main/resources/templates/ehr_link_set_template.mustache, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_1.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_10.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_11.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_12.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_13.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_14.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_2.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_3.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_4.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_5.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_6.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_7.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_8.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_9.xml, service/src/test/resources/ehr/mapper/encountercomponents/expected-components-1.xml, service/src/test/resources/ehr/request/fhir/output/expected-ehr-extract-response-from-json.xml, service/src/test/resources/uat/output/TC4-9465698490_Daniels_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465698679_Gainsford_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465699918_Magre_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465699926_Sajal_full_20210122.xml, service/src/test/resources/uat/output/TC4-9465701262_Meyers_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701297_Livermore_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701459_Nel_full_20210119.xml
* Added statusCode to RequestStatement template
* Updated test resource files accordingly
=> NIAD-1429: Condition LinkSet added statusCode

service/src/main/resources/templates/ehr_medication_statement_authorise_template.mustache, service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-acute-prescription.xml, service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-default-status-reason-code.xml, service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-optional-fields.xml, service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-repeat-prescription-no-value.xml, service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-repeat-prescription.xml, service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-authorise-start-period-only.xml, service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-dispense-quantity-text.xml, service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-no-dispense-quantity-text.xml, service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-no-dispense-quantity-value.xml, service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-prescribe-prior-prescription.xml, service/src/test/resources/uat/output/TC4-9465698490_Daniels_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465699918_Magre_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701262_Meyers_full_20210119.xml
* Updated MedicationStatement Authorise template to include priorMedicationRef tag
* Updated test resource files accordingly
=> NIAD-1431: MedicationRequest added priorMedicationRef to ehrSupplyDiscontinue

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/BloodPressureMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/BloodPressureParameters.java, service/src/main/resources/templates/ehr_compound_statement_blood_pressure_template.mustache, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/BloodPressureMapperTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/uat/EhrExtractUATTest.java, service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-with-data.xml, service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-with-diastolic-data-only.xml, service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-with-period-date.xml, service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-with-systolic-data-only.xml, service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-without-data.xml, service/src/test/resources/ehr/mapper/blood_pressure/arterial-pressure-without-effective-date.xml, service/src/test/resources/ehr/mapper/blood_pressure/blood-pressure-with-codeable-concepts.xml, service/src/test/resources/ehr/mapper/blood_pressure/blood-pressure-with-data-nested.xml, service/src/test/resources/ehr/mapper/blood_pressure/blood-pressure-with-data.xml, service/src/test/resources/ehr/mapper/blood_pressure/blood-pressure-without-data.xml, service/src/test/resources/ehr/mapper/blood_pressure/empty-observation.xml, service/src/test/resources/ehr/mapper/blood_pressure/observation-with-no-valid-code.xml, service/src/test/resources/ehr/mapper/encountercomponents/expected-components-1.xml, service/src/test/resources/ehr/request/fhir/output/expected-ehr-extract-response-from-json.xml, service/src/test/resources/uat/output/TC4-9465699926_Sajal_full_20210122.xml, service/src/test/resources/uat/output/TC4-9465700339_Yamura_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701297_Livermore_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701459_Nel_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701483_Dougill_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701483_Nel_full_20210119.xml
* BloodPressure mapping now translates performer to Participant, follows same logic as Uncategorised Observation, as per mapping spreadsheet.
* Updated relevant test files
=> NIAD-1432: BloodPressure missing agent

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DiaryPlanStatementMapper.java, service/src/main/resources/templates/ehr_plan_statement_template.mustache, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DiaryPlanStatementMapperTest.java, service/src/test/resources/ehr/mapper/procedurerequest/expected-plan-statement-1.xml, service/src/test/resources/ehr/mapper/procedurerequest/expected-plan-statement-8.xml, service/src/test/resources/ehr/request/fhir/output/expected-ehr-extract-response-from-json.xml, service/src/test/resources/uat/output/TC4-9465698490_Daniels_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465698679_Gainsford_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465699918_Magre_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465699926_Sajal_full_20210122.xml, service/src/test/resources/uat/output/TC4-9465700193_Birdi_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465700339_Yamura_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701262_Meyers_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701297_Livermore_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701459_Nel_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701483_Dougill_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701483_Nel_full_20210119.xml
PlanStatement/Participant maps to both author/agentRef and Participant2/@typeCode='PPRF'.
author/time holds the same value as effectiveTime
=> NIAD-1426: Add agents to mapped procedure request

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapper.java, service/src/test/resources/ehr/request/fhir/output/ExpectedResponseFrom1ConsultationResponse.xml, service/src/test/resources/ehr/request/fhir/output/expected-xml-with-effective-time.xml, service/src/test/resources/ehr/request/fhir/output/expected-xml-without-effective-time.xml, service/src/test/resources/ehr/request/fhir/output/expected-xml-without-high-effective-time.xml, service/src/test/resources/uat/output/TC4-9465701262_Meyers_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701297_Livermore_full_20210119.xml
... so that they don't end up in the output as ehrComposition elements without any components.
=> NIAD-1378 Ignore empty Encounter elements when mapping EHR extract

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AllergyStructureMapper.java, service/src/test/resources/JsonToXml/Output/sampleJson2.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-1.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-10.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-12.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-13.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-14.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-2.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-3.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-4.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-5.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-6.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-8.xml, service/src/test/resources/ehr/mapper/allergy/expected-output-allergy-structure-9.xml, service/src/test/resources/ehr/mapper/encountercomponents/expected-components-1.xml, service/src/test/resources/ehr/mapper/non_consultation_bundles/allergy-intolerance-stub.xml, service/src/test/resources/ehr/mapper/non_consultation_bundles/expected-allergy-intolerance-output.xml, service/src/test/resources/ehr/request/fhir/output/ExpectedResponseFrom1ConsultationResponse.xml, service/src/test/resources/ehr/request/fhir/output/expected-ehr-extract-response-from-json.xml, service/src/test/resources/ehr/request/fhir/output/expected-xml-without-effective-time.xml, service/src/test/resources/uat/output/TC4-9465698490_Daniels_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465698679_Gainsford_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465699918_Magre_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465699926_Sajal_full_20210122.xml, service/src/test/resources/uat/output/TC4-9465700339_Yamura_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701297_Livermore_full_20210119.xml, service/src/test/resources/uat/output/TC4-9465701459_Nel_full_20210119.xml
Fix minor issue with drug allergy code in XML output.
=> NIAD-1474: Fix drug allergy code.

CHANGELOG.md, release/DOCKERHUB.md, release/version.sh
=> NIAD-1746: Release 1.3.1

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementExtractor.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapper.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapperTest.java, service/src/test/resources/ehr/mapper/medication_request/medication-request-with-plan-quantity-quantity-text.json, service/src/test/resources/ehr/mapper/medication_request/medication-statement-with-quantity-quantity-text.xml
Bug fix for [NIAD-1667](https://gpitbjss.atlassian.net/browse/NIAD-1667)
=> NIAD-1667: MedicationRequest: quantityText is not being processed

service/src/main/resources/templates/observation_statement_template.mustache, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapperTest.java, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_with_reference_range_and_interpretation.xml, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_with_reference_range_and_interpretation.json
Bug fix for [NIAD-1779](https://gpitbjss.atlassian.net/browse/NIAD-1779)
=> NIAD-1779: DiagnosticReport: interpretationCode is output in wrong place

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapper.java, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_1.xml, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_2.xml, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_3.xml, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_with_data_absent_reason_and_interpretation_and_body_site_and_method.xml, service/src/test/resources/ehr/mapper/encountercomponents/expected-components-1.xml, service/src/test/resources/uat/output/TC4/9465700088_Mold_full_20210119.xml, service/src/test/resources/uat/output/TC4/9465701718_Guerra_full_20210119.xml, service/src/test/resources/uat/output/TC7/9465700088_Mold_full_20210602.xml, service/src/test/resources/uat/output/TC7/9465701718_Guerra_full_20210602.xml
[NIAD-1764](https://gpitbjss.atlassian.net/browse/NIAD-1764) fix
=> NIAD-1764: DiagnosticReport: Align CompoundStatement CLUSTER dates with ObservationStatement dates

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/SpecimenMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/DateFormatUtil.java, service/src/test/java/uk/nhs/adaptors/gp2gp/utils/DateFormatUtilTest.java, service/src/test/resources/ehr/mapper/diagnosticreport/specimen/expected-specimen-with-empty-duration-value.xml, service/src/test/resources/ehr/mapper/diagnosticreport/specimen/expected-specimen-with-empty-quantity-value.xml, service/src/test/resources/ehr/mapper/diagnosticreport/specimen/expected-specimen-without-body-site.xml, service/src/test/resources/ehr/mapper/diagnosticreport/specimen/expected-specimen-without-fasting-duration.xml, service/src/test/resources/ehr/mapper/diagnosticreport/specimen/expected-specimen-without-fasting-status.xml, service/src/test/resources/ehr/mapper/diagnosticreport/specimen/expected-specimen-without-notes.xml, service/src/test/resources/ehr/mapper/diagnosticreport/specimen/expected-specimen-without-quantity.xml, service/src/test/resources/ehr/mapper/diagnosticreport/specimen/expected-specimen.xml, service/src/test/resources/uat/output/TC4/9465700088_Mold_full_20210119.xml, service/src/test/resources/uat/output/TC4/9465701718_Guerra_full_20210119.xml, service/src/test/resources/uat/output/TC7/9465700088_Mold_full_20210602.xml, service/src/test/resources/uat/output/TC7/9465701718_Guerra_full_20210602.xml
[NIAD-1760](https://gpitbjss.atlassian.net/browse/NIAD-1760) bug fix
=> NIAD-1760: DiagnosticReport: Add Specimen received date to the specimen as notes text

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapper.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapperTest.java, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_with_data_absent_reason_and_interpretation_and_body_site_and_method.xml, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_with_interpretation_code_abnormal.xml, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_with_interpretation_code_low.xml, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_with_multiple_interpretations.xml, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_with_referencerange_in_comment.xml, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_compound_statement_with_value_quantity_and_reference_range.xml, service/src/test/resources/ehr/mapper/diagnosticreport/observation/observation_with_referencerange_and_no_valuequantity.json
Ticket -> [NIAD-1778](https://gpitbjss.atlassian.net/browse/NIAD-1778)
=> NIAD-1778: DiagnosticReport: ReferenceRange is being lost entirely if no valueQuantity

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/IdMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/DiagnosticReportMapper.java, service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-coded-diagnosis.xml, service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-conclusion.xml, service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-extension-id.xml, service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-multi-specimens.xml, service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-multiple-coded-diagnosis.xml, service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-multiple-results.xml, service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-one-specimen.xml, service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-participant.xml, service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-required-data.xml, service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-status-narrative.xml, service/src/test/resources/ehr/mapper/encountercomponents/expected-components-1.xml, service/src/test/resources/ehr/request/fhir/output/expected-xml-with-standalone-observations.xml, service/src/test/resources/uat/input/TC7/9465700088_Mold_full_20210602.json, service/src/test/resources/uat/output/TC4/9465699926_Sajal_full_20210122.xml, service/src/test/resources/uat/output/TC4/9465700088_Mold_full_20210119.xml, service/src/test/resources/uat/output/TC4/9465701718_Guerra_full_20210119.xml, service/src/test/resources/uat/output/TC7/9465700088_Mold_full_20210602.xml, service/src/test/resources/uat/output/TC7/9465701718_Guerra_full_20210602.xml
Stopped duplication of mapping observations
=> NIAD-1676: Testing feedback fixes

transformJsonToXml/input/.gitignore
Ticket -> [NIAD-1916](https://gpitbjss.atlassian.net/browse/NIAD-1916)
=> NIAD-1916: Add .gitignore file to TransformJsonToXml tool's input folder

service/src/main/java/uk/nhs/adaptors/gp2gp/common/utils/BinaryUtils.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusService.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/SendDocumentTaskExecutor.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/SendEhrExtractCoreTaskExecutor.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/model/EhrExtractStatus.java, service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcDocumentTaskExecutor.java, service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcStructuredTaskExecutor.java, service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GpcDocumentTranslator.java, service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/StructuredRecordMappingService.java, service/src/main/java/uk/nhs/adaptors/gp2gp/mhs/model/OutboundMessage.java, service/src/test/java/uk/nhs/adaptors/gp2gp/gpc/GpcDocumentTranslatorTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/gpc/StructuredRecordMappingServiceTest.java
Updated method used to calculate size of attachment
=> NIAD-1931: incorrect-length

service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcStructuredTaskExecutor.java
An additional fix for [NIAD-1914](https://gpitbjss.atlassian.net/browse/NIAD-1914)
=> NIAD-1914: QuickFix - Adding AbsentAttachments to OutboundMessage

CHANGELOG.md, release/DOCKERHUB.md, release/version.sh
Added release info to change log and altered release number.
=> Niad 2114 release 1.5.0 - added release info

CHANGELOG.md, release/DOCKERHUB.md, release/version.sh, service/build.gradle
Upgrade vulnerable dependencies and update documentation for new release.
=> NIAD-2340-Release-1.5.2

CHANGELOG.md
=> Update changelog for release 1.5.6

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ConditionLinkSetMapper.java, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_16.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_17.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_18.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_19.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_20.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_3.xml, service/src/test/resources/ehr/mapper/condition/expected_output_linkset_5.xml, service/src/test/resources/ehr/request/fhir/output/expected-ehr-extract-response-from-json.xml
Coding changes and unit test changes to update availability time to correct json resource against the GP2GP mapping specification. Issue identified by AG in run 1 testing.
=> task_2590 to main

docker/wiremock/stubs/__files/correctAllergiesContainedResourceResponse.json, docker/wiremock/stubs/mappings/retrieveContainedAllergiesList.json, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ConditionLinkSetMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/ResourceExtractor.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/utils/AllergyStructureExtractorTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/utils/ResourceExtractorTest.java, service/src/test/resources/ehr/mapper/listresource/fhir_bundle.json
This PR is to address resource matching issues for List Resource. There are some cases when list resource includes contained elements and reference is provided for the contained reference and in such cases the resource wasn't found. So this PR improves matching so that contained resources are able to be found and resolved.
=> NIAD-2807: Resolve allergy resource matching when it is contained in list

service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcStructuredTaskExecutor.java, service/src/test/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcStructuredTaskExecutorTest.java
This basic unit test will make adding more tests/behaviour easier
=> NIAD-2812: Add unit test for GetGpcStructuredTaskExecutor

CHANGELOG.md, developer-information.md
=> Added new release note to CHANGELOG.md and added deployment info

service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcDocumentTaskExecutor.java
Might save some time for the next person who comes along and looks into this code.
Documentation 📚!
=> Add comment to GetGpcDocumentTaskExecutor warning about memory usage

CHANGELOG.md
=> Updated CHANGELOG.md to version 1.5.12

.github/dependabot.yml
Enable [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) for gradle
Automatic upgrading of dependencies should help us keep the adaptor more secure and maintainable.
=> Enable Dependabot for gradle

OPERATING.md
Help our users understand what limitations exist on other systems, which will hopefully prevent queries coming to our support team.
📚 Documentation improvement!
=> Document limits identified on receiving systems

service/build.gradle
It doesn't appear to be in use
=> Remove envkeystore dependency

developer-information.md
Based off of some trouble we had this morning.
=> Update developer troubleshooting guidance

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/IdMapper.java
=> Add JavaDoc to IdMapper class explaining its purpose

docker/wiremock/README.md, docker/wiremock/stubs/mappings/retrieveContainedAllergiesList.json
This should help me when I want to test a specific scenario
=> Document each of the different migratestructuredrecord scenarios

CHANGELOG.md, release/version.sh
=> Release version 2.0.0

e2e-tests/src/main/java/uk/nhs/adaptors/gp2gp/Mongo.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/TaskHandlingTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/testcontainers/ActiveMQExtension.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/testcontainers/WiremockExtension.java, service/src/main/java/uk/nhs/adaptors/gp2gp/common/configuration/CustomTrustStore.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AgentDirectoryExtractor.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AllergyStructureExtractor.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AllergyStructureMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DiaryPlanStatementMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ImmunizationObservationStatementMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationStatementMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationValueQuantityMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/SpecimenMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/wrapper/ConditionWrapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/status/service/EhrStatusRequestsService.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/AbsentAttachmentUtils.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/SupportingInfoResourceExtractor.java, service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GpcTemplateUtils.java, service/src/main/java/uk/nhs/adaptors/gp2gp/transformJsonToXmlTool/TransformJsonToXml.java
Small code optimizations
Keeping code clean and tidy is a good thing to have
=> Small code optimizations

service/build.gradle
For each of the constraints, they were either
- Downgrading a package would would be a more recent version otherwise
- Having no effect on the version of the packages used
=> Remove unnecessary constraints from build.gradle

docker/mock-mhs-adaptor/Dockerfile, docker/service/Dockerfile
Extends security patching support for another 2 years.
=> Upgrade from Ubuntu Focal to Ubuntu Jammy

.github/dependabot.yml
Keeps packages up to date within supporting services.
=> Turn on Dependabot for more gradle packages

.github/workflows/release.yml
- [x ] Internal change (non-breaking change with no effect on the functionality affecting end users)
- [ x] I have performed a self-review of my code
=> Adaptor release for docker image build.

developer-information.md
=> Update release instructions

e2e-tests/build.gradle
=> Remove unused test dependency xmlunit-matchers

service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusTestUtils.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/SendEhrExtractCoreComponentTest.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/SendEhrExtractCoreTaskExecutor.java
=> NIAD-2394: Add additional unit tests around existing SendEhrExtractCoreTaskExecutor

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusService.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/GetAbsentAttachmentTaskExecutor.java, service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcDocumentTaskExecutor.java, service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GpcFilenameUtils.java
=> Rename filename to storagePath to be clearer about which it is

service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusServiceTest.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusService.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/GetAbsentAttachmentTaskExecutor.java, service/src/main/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcDocumentTaskExecutor.java
=> Simplify the parameters of updateEhrExtractStatusAccessDocument

README.md
Hopefully makes the diagram more visible to users
=> Add sequence diagram to README

wiremock/README.md, wiremock/stubs/__files/correct3_5MBDocumentResponse.json, wiremock/stubs/__files/correctPatientStructuredRecordResponse350MBDocuments.json, wiremock/stubs/mappings/migrateStructuredRecord 350MB Attachments.json, wiremock/stubs/mappings/retrieve3_5MBDocumentResponse.json
Will help testing the non-functional behaviour of the adaptor
=> Add in Wiremock scenario for patient with 350MB of attachments

CHANGELOG.md
=> [NIAD-3112] Update CHANGELOG.md

developer-information.md, docker/e2e-tests/Dockerfile, docker/mock-mhs-adaptor/Dockerfile, docker/service/Dockerfile, docker/wiremock/Dockerfile, e2e-tests/build.gradle, mock-mhs-adaptor/build.gradle, service/build.gradle
Gives us a couple of years of Long Term Support, and some new features in Java.
=> Upgrade to Java 21

wiremock/README.md, wiremock/stubs/__files/correct10MBDocumentResponse.json, wiremock/stubs/__files/correctPatientStructuredRecordResponse10MBAttachment.json, wiremock/stubs/mappings/migrateStructuredRecord 10MB Attachment.json, wiremock/stubs/mappings/retrieve10MBDocumentResponse.json
To help E2E test fragments with the GP2GP adaptor.
=> Add patient with 10MB Document to wiremock

service/src/intTest/java/uk/nhs/adaptors/gp2gp/common/configuration/RedactionsConfigurationTest.java, service/src/main/java/uk/nhs/adaptors/gp2gp/common/configuration/RedactionsConfiguration.java
=> Refactor: Remove the duplicated constants to simplify

service/src/main/resources/templates/ehr_allergy_structure_template.mustache
Updated `ehr_allergy_structure_template.mustache` to ensure `confidentialityCode` is in the correct location in the XML as per the Schema.
As per the schema, `confidentialityCode` should appear after `availabilityTime`.  Although this will not cause schema validation to fail, it is best practice to match the schema ordering.
```xsd
<xs:complexType name="RCMR_MT030101UK05.CompoundStatement">
<xs:sequence>
<xs:element name="id" type="II" minOccurs="1" maxOccurs="2"/>
<xs:element name="code" type="CD" minOccurs="1" maxOccurs="1"/>
<xs:element name="statusCode" type="CS" minOccurs="1" maxOccurs="1"/>
<xs:element name="effectiveTime" type="IVL_TS" minOccurs="1" maxOccurs="1"/>
<xs:element name="availabilityTime" type="TS" minOccurs="1" maxOccurs="1"/>
<xs:element name="priorityCode" type="CV" …
```
=> Move `confidentialityCode` in moustache template to schema position

wiremock/README.md, wiremock/stubs/__files/EMISPatientStructurede2eResponsePWTP3.json, wiremock/stubs/mappings/migrateStructuredRecord PWTP3.json
To help testing of the GP2GP Adaptor within the PTL environment.
=> Add PWTP3 as a selectable scenario for Wiremock

.github/workflows/build_workflow.yml, scripts/create_build_id.sh
This pull request addresses an issue encountered during the testing phase of the new workflow. Specifically, the Jenkinsfile relies on the GIT_BRANCH environment variable provided by the Git plugin. To ensure compatibility with GitHub Actions, this PR implements a method to manually replicate the functionality of the GIT_BRANCH environment variable. This change facilitates the seamless integration of branch information into GitHub Actions, aligning with the workflow requirements and ensuring consistency across CI/CD platforms.
=> NIAD-3173 - Fix Docker image tagging mechanism so that ECR lifecycle policies pick up orphan images

service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java, service/src/test/resources/ehr/mapper/encountercomponents/expected-components-18-related-problem-invalid-extension.xml, service/src/test/resources/ehr/mapper/encountercomponents/input-bundle-18-related-problem-invalid-problem-extension.json
Add missing test to verify that an unspecified problem is produced when a related problem has an incorrect problem extension url.
The test was missing, so this existing functionality was not covered by tests
=> NIAD-3137 - Add missing test for unspecified problem

service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/utils/MedicationRequestUtilsTest.java
=> Fix checkstyle errors

service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrAcknowledgementTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusServiceIT.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusService.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusServiceTest.java
Logging format optimization
Logging is much more readable if it follows a uniform standard
=> NIAD-2840: log messages optimization

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusService.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusServiceTest.java
A small fix for MongoDB update procedure
During the test a small issue has been identified where MongoDB didn't recognize the path of the updated record.
=> NIAD-2840: small post test fixes

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DocumentReferenceToNarrativeStatementMapper.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DocumentReferenceToNarrativeStatementMapperTest.java
Small test refactoring and small logging message adjustment
Small logging message adjustment to make it a little bit more descriptive
=> Post NIAD-3151 refactoring

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DiaryPlanStatementMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapper.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DiaryPlanStatementMapperTest.java
Original design caused some confusion, hoping this refactoring will reduce future confusion.
=> Refactoring DiaryPlanStatementMapper 

CHANGELOG.md
=> Add 2.1.0 to CHANGELOG.md

service/build.gradle, service/src/main/java/uk/nhs/adaptors/gp2gp/common/configuration/CustomTrustStore.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/XpathExtractor.java, service/src/test/java/uk/nhs/adaptors/gp2gp/gpc/TaskExecutorFactoryTest.java
Add support for Java 21 pattern matching syntax.
=> Upgrade checkstyle to latest version

CHANGELOG.md
=> Add 2.1.1 to CHANGELOG.md

OPERATING.md
=> Clarify the retry delay mechanism in OPERATING.md

README.md
These are a useful starting point for somebody wanting to get the adaptor working.
=> Add link to GP2GP Getting Started guidance

CHANGELOG.md
=> Add 2.1.3 to CHANGELOG.md

wiremock/README.md, wiremock/stubs/__files/correct30MBDocumentResponse.json, wiremock/stubs/__files/correctPatientStructuredRecordResponse30MBAttachment.json, wiremock/stubs/mappings/migrateStructuredRecord 30MB Attachment.json, wiremock/stubs/mappings/retrieve30MBDocumentResponse.json
Helps test NIAD-3228 where we were seeing an issue with 20MB attachments.
=> Inrease size of large document patient from 10MB to 30MB

wiremock/stubs/__files/correctPatientStructuredRecordResponse30MBAttachment.json
=> Fix description of 30MB attachment

service/build.gradle
According to the SonarQube docs this will then get picked up by the sonar gradle plugin, providing coverage information within SonarQube Cloud
=> Write out JaCoCo coverage report to build folder

CHANGELOG.md
=> Improve the Specimenless fix description in CHANGELOG.md

service/src/test/java/uk/nhs/adaptors/gp2gp/common/service/FhirParseServiceTest.java
Tests to cover JSON FHIR conversion
JSON converter in FhirParseService converts resources with additional options (PrettyPrint) which is good to cover with tests so that we know that it works as intended. 
=> Adding tests for json fhir convertion

CHANGELOG.md
=> Add 2.2.0 to CHANGELOG.md

service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/NonConsultationResourceMapperTest.java
=> Allow whitespace differences when comparing expected and actual XML

gp2gp_adaptor_response_docs.yaml
OpenApi Spec update
The information about the health check was added. Also tags were slightly regrouped.
=> NIAD-3234: openapi spec update

CHANGELOG.md
Add 2.2.1 to CHANGELOG.md 
Updated changelog after new release.
- [] New and existing unit tests pass locally with my changes
=> Add 2.2.1 to CHANGELOG.md

service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AgentDirectoryMapperTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AgentDirectoryTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/AllergyStructureMapperTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterMapperTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/scheduling/EhrExtractTimeoutSchedulerTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/status/service/EhrStatusBaseServiceTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/status/service/EhrStatusServiceTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/utils/EncounterExtractorTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/utils/ResourceExtractorTest.java
=> Code cleanup

service/build.gradle, service/src/test/java/uk/nhs/adaptors/gp2gp/common/storage/S3StorageConnectorTest.java
Test refactoring
Refactoring test to eliminate the usage of mocks and replacing them with real objects which is always preferable
=> NIAD-3208: test refactoring

OPERATING.md, docker/docker-compose.yml
⚠️ Will need to think about how we deal with this, is a breaking change to upgrade the minimum version ⚠️ 
=> Upgrade minimum version of MongoDB required for the adaptor

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/DiagnosticReportMapper.java
This was picked up by pitest as being unnecessary.
=> Remove unnecessary if statement

README.md, docker/service/Dockerfile, service/settings.gradle
=> Rename project to GP2GP FHIR Send Adaptor

wiremock/stubs/__files/EMISPatientStructurede2eResponsePWTP3.json
Help testing E2E behaviour of Drug and Non-Drug intolerances
=> Add NOPAT confidentiality code to Asprin and cow milk allergies

wiremock/README.md, wiremock/stubs/mappings/migrateStructuredRecord PWTP6.json
Will help test out behaviour of Imunization mapping within incumbents.
=> Add Immunisations scenario to Wiremock

service/src/intTest/java/uk/nhs/adaptors/gp2gp/common/amqp/AmqpServiceFailureTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/TaskHandlingTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcDocumentComponentTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcStructuredComponentTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/gpc/GpcWebClientTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/mhs/MhsWebClientTest.java
=> Replace deprecated SpyBean with MockitoSpyBean

wiremock/stubs/__files/EMISPatientStructurede2eResponsePWTP6.json
=> Test out NOPAT for Immunizations

service/src/intTest/java/uk/nhs/adaptors/gp2gp/common/amqp/MessageQueueTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/common/task/BaseTaskTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrContinueTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/EhrExtractStatusServiceIT.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/SendAcknowledgementComponentTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/SendDocumentComponentTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/SendEhrExtractCoreComponentTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/ehr/TaskHandlingTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcDocumentComponentTest.java, service/src/intTest/java/uk/nhs/adaptors/gp2gp/gpc/GetGpcStructuredComponentTest.java
=> Replace all usages of deprecated MockBean with MockitoBean

wiremock/README.md, wiremock/stubs/__files/EMISPatientStructurede2eResponsePWTP9.json, wiremock/stubs/mappings/migrateStructuredRecord PWTP9.json
Also add some NOPAT configuration to some of the Resources to help test confidentiality code functionality.
=> Add PWTP9 (Patient with lots of investigations) Wiremock scenario

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapper.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapperTest.java, service/src/test/resources/ehr/mapper/medication_request/mr-plan-with-invalid-prescription-type.json
* Update message to be clearer and more informative to the user.
* Add test to ensure exception is thrown and the message is correct.
* Add input JSON file for the above test
The exception message was not clear when an exception was thrown due to a invalid prescription type.
There was also no tests to cover this functionality.
=> Update invalid prescription type exception when mapping MedicationStatement

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapper.java
* Refactor `mapCodeableConceptToCd` method in `CodeableConceptCdMapper` 
For readability and to easier allow modification for NIAD-3304 functionality.
=> NIAD-3304: Refactor mapCodeableConceptToCd method

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/CodeableConceptCdMapper.java
* Remove unused code when getting original text for null-flavor codeable concepts.
* Use existing method for get the display value from a description extension.
* Refactor for readability and code clarity.
Refactoring for code quality and clarity
=> Remove unused code when getting original text for null-flavor codeable concepts.

CHANGELOG.md, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/BloodPressureMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/BloodPressureParameters.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/RequestStatementTemplateParameters.java, service/src/main/resources/templates/ehr_compound_statement_blood_pressure_template.mustache, service/src/main/resources/templates/ehr_request_statement_template.mustache, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/BloodPressureMapperTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapperTest.java
Temporary disabling changes introduced in NIAD-3153 and NIAD-3154
In order to move with a release we would like to temporarily disable the changes introduced earlier
=> Temporary disabling changes introduced in NIAD-3153 and NIAD-3154

CHANGELOG.md
Update Changelog for release 2.3.0
Update Changelog for release 2.3.0
=> Update Changelog for release 2.3.0

service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapper.java, service/src/main/resources/templates/ehr_request_statement_template.mustache
Schema adjustments
Generated XML should follow XSD schema
=> NIAD-3153: schema adjustments

CHANGELOG.md
New changelog update for 2.4.0 release
=> Changelog update for 2.4.0 release

service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperComponentTest.java, service/src/test/resources/ehr/request/fhir/input/gpc-access-structured-with-nopat.json, service/src/test/resources/ehr/request/fhir/output/expected-ehr-extract-response-from-json-with-nopat.xml
Adding an additional test to increase test coverage for uncategorized observation
This is a support test for end-to-end testing scenario
=> NIAD-3157: increased test coverage for uncategorized observation

CHANGELOG.md, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapper.java, service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/parameters/CompoundStatementParameters.java, service/src/main/resources/templates/ehr_compound_statement_template.mustache, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EhrExtractMapperComponentTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapperTest.java, service/src/test/java/uk/nhs/adaptors/gp2gp/uat/EhrExtractUATTest.java, service/src/test/resources/ehr/mapper/encountercomponents/expected-components-with-nopat.xml, service/src/test/resources/ehr/mapper/encountercomponents/input-bundle-10-with-meta.json
Send over List (Topic).meta.security NOPAT field to incumbent
This change aims to make List Topic Redactions-compliant
=> NIAD-3290: Send over List (Topic).meta.security NOPAT field to incumbent
